/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, clang++ 18.1.8 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "comparator.sv:1.1-21.10" *)
module comparator(A, B, U, EQ, LT);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  (* src = "comparator.sv:6.19-6.20" *)
  wire _042_;
  (* src = "comparator.sv:6.19-6.20" *)
  wire _043_;
  (* src = "comparator.sv:6.19-6.20" *)
  wire _044_;
  (* src = "comparator.sv:6.19-6.20" *)
  wire _045_;
  (* src = "comparator.sv:6.19-6.20" *)
  wire _046_;
  (* src = "comparator.sv:6.19-6.20" *)
  wire _047_;
  (* src = "comparator.sv:6.19-6.20" *)
  wire _048_;
  (* src = "comparator.sv:6.19-6.20" *)
  wire _049_;
  (* src = "comparator.sv:7.19-7.20" *)
  wire _050_;
  (* src = "comparator.sv:7.19-7.20" *)
  wire _051_;
  (* src = "comparator.sv:7.19-7.20" *)
  wire _052_;
  (* src = "comparator.sv:7.19-7.20" *)
  wire _053_;
  (* src = "comparator.sv:7.19-7.20" *)
  wire _054_;
  (* src = "comparator.sv:7.19-7.20" *)
  wire _055_;
  (* src = "comparator.sv:7.19-7.20" *)
  wire _056_;
  (* src = "comparator.sv:7.19-7.20" *)
  wire _057_;
  (* src = "comparator.sv:9.19-9.21" *)
  wire _058_;
  (* src = "comparator.sv:10.19-10.21" *)
  wire _059_;
  (* src = "comparator.sv:8.19-8.20" *)
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  (* src = "comparator.sv:6.19-6.20" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "comparator.sv:7.19-7.20" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "comparator.sv:9.19-9.21" *)
  output EQ;
  wire EQ;
  (* src = "comparator.sv:10.19-10.21" *)
  output LT;
  wire LT;
  (* src = "comparator.sv:8.19-8.20" *)
  input U;
  wire U;
  NOT _092_ (
    .A(_042_),
    .Y(_061_)
  );
  NOT _093_ (
    .A(_043_),
    .Y(_062_)
  );
  NOT _094_ (
    .A(_046_),
    .Y(_063_)
  );
  NOT _095_ (
    .A(_047_),
    .Y(_064_)
  );
  NOT _096_ (
    .A(_057_),
    .Y(_065_)
  );
  NAND2B _097_ (
    .A_N(_048_),
    .B(_056_),
    .Y(_066_)
  );
  NAND2B _098_ (
    .A_N(_056_),
    .B(_048_),
    .Y(_067_)
  );
  NAND2 _099_ (
    .A1(_049_),
    .A2(_065_),
    .Y(_068_)
  );
  NOR2 _100_ (
    .A1(_049_),
    .A2(_065_),
    .Y(_069_)
  );
  XNOR2 _101_ (
    .A(_049_),
    .B(_057_),
    .Y(_070_)
  );
  AND3 _102_ (
    .A1(_066_),
    .A2(_067_),
    .A3(_070_),
    .Y(_071_)
  );
  NOR2 _103_ (
    .A1(_064_),
    .A2(_055_),
    .Y(_072_)
  );
  NAND2 _104_ (
    .A1(_064_),
    .A2(_055_),
    .Y(_073_)
  );
  XNOR2 _105_ (
    .A(_046_),
    .B(_054_),
    .Y(_074_)
  );
  NAND4B _106_ (
    .A1_N(_072_),
    .A2(_073_),
    .A3(_074_),
    .A4(_071_),
    .Y(_075_)
  );
  NAND2B _107_ (
    .A_N(_053_),
    .B(_045_),
    .Y(_076_)
  );
  NAND2B _108_ (
    .A_N(_052_),
    .B(_044_),
    .Y(_077_)
  );
  NAND2 _109_ (
    .A1(_076_),
    .A2(_077_),
    .Y(_078_)
  );
  NAND2B _110_ (
    .A_N(_045_),
    .B(_053_),
    .Y(_079_)
  );
  NAND2B _111_ (
    .A_N(_044_),
    .B(_052_),
    .Y(_080_)
  );
  AND4 _112_ (
    .A1(_076_),
    .A2(_077_),
    .A3(_079_),
    .A4(_080_),
    .Y(_081_)
  );
  AOI22 _113_ (
    .A1(_061_),
    .A2(_050_),
    .B1(_062_),
    .B2(_051_),
    .Y(_082_)
  );
  NOR2 _114_ (
    .A1(_062_),
    .A2(_051_),
    .Y(_083_)
  );
  NAND2B _115_ (
    .A_N(_050_),
    .B(_042_),
    .Y(_084_)
  );
  NAND4B _116_ (
    .A1_N(_083_),
    .A2(_084_),
    .A3(_081_),
    .A4(_082_),
    .Y(_085_)
  );
  NOR2 _117_ (
    .A1(_075_),
    .A2(_085_),
    .Y(_058_)
  );
  OAI21 _118_ (
    .A(_081_),
    .B1(_082_),
    .B2(_083_),
    .Y(_086_)
  );
  NAND2 _119_ (
    .A1(_078_),
    .A2(_079_),
    .Y(_087_)
  );
  AOI21 _120_ (
    .A1(_086_),
    .A2(_087_),
    .B1(_075_),
    .Y(_088_)
  );
  AOI22 _121_ (
    .A1(_060_),
    .A2(_069_),
    .B1(_070_),
    .B2(_067_),
    .Y(_089_)
  );
  AOI211 _122_ (
    .A(_063_),
    .B(_054_),
    .C1(_064_),
    .C2(_055_),
    .Y(_090_)
  );
  OA21 _123_ (
    .A(_071_),
    .B1(_072_),
    .B2(_090_),
    .Y(_091_)
  );
  OAI32 _124_ (
    .A1(_088_),
    .A2(_089_),
    .A3(_091_),
    .B1(_068_),
    .B2(_060_),
    .Y(_059_)
  );
  assign _042_ = A[0];
  assign _050_ = B[0];
  assign _043_ = A[1];
  assign _051_ = B[1];
  assign _044_ = A[2];
  assign _052_ = B[2];
  assign _045_ = A[3];
  assign _053_ = B[3];
  assign _046_ = A[4];
  assign _054_ = B[4];
  assign _047_ = A[5];
  assign _055_ = B[5];
  assign _048_ = A[6];
  assign _056_ = B[6];
  assign _049_ = A[7];
  assign _057_ = B[7];
  assign EQ = _058_;
  assign _060_ = U;
  assign LT = _059_;
endmodule
