/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, clang++ 18.1.8 -fPIC -O3) */

module alu32(A, B, S, nCout);
  input [31:0] A;
  wire [31:0] A;
  input [31:0] B;
  wire [31:0] B;
  output [31:0] S;
  wire [31:0] S;
  output nCout;
  wire nCout;
  wire nG0_7;
  wire nG16_23;
  wire nG8_15;
  wire \u_0_7.A[0] ;
  wire \u_0_7.A[1] ;
  wire \u_0_7.A[2] ;
  wire \u_0_7.A[3] ;
  wire \u_0_7.A[4] ;
  wire \u_0_7.A[5] ;
  wire \u_0_7.A[6] ;
  wire \u_0_7.A[7] ;
  wire \u_0_7.B[0] ;
  wire \u_0_7.B[1] ;
  wire \u_0_7.B[2] ;
  wire \u_0_7.B[3] ;
  wire \u_0_7.B[4] ;
  wire \u_0_7.B[5] ;
  wire \u_0_7.B[6] ;
  wire \u_0_7.B[7] ;
  wire \u_0_7.S[0] ;
  wire \u_0_7.S[1] ;
  wire \u_0_7.S[2] ;
  wire \u_0_7.S[3] ;
  wire \u_0_7.S[4] ;
  wire \u_0_7.S[5] ;
  wire \u_0_7.S[6] ;
  wire \u_0_7.S[7] ;
  wire \u_0_7._092_ ;
  wire \u_0_7._093_ ;
  wire \u_0_7._094_ ;
  wire \u_0_7._095_ ;
  wire \u_0_7._096_ ;
  wire \u_0_7._097_ ;
  wire \u_0_7._098_ ;
  wire \u_0_7._099_ ;
  wire \u_0_7._101_ ;
  wire \u_0_7._102_ ;
  wire \u_0_7._103_ ;
  wire \u_0_7._104_ ;
  wire \u_0_7._105_ ;
  wire \u_0_7._106_ ;
  wire \u_0_7._107_ ;
  wire \u_0_7._108_ ;
  wire \u_0_7._109_ ;
  wire \u_0_7._110_ ;
  wire \u_0_7._111_ ;
  wire \u_0_7._112_ ;
  wire \u_0_7._113_ ;
  wire \u_0_7._114_ ;
  wire \u_0_7._115_ ;
  wire \u_0_7._116_ ;
  wire \u_0_7._117_ ;
  wire \u_0_7._118_ ;
  wire \u_0_7._119_ ;
  wire \u_0_7._120_ ;
  wire \u_0_7._121_ ;
  wire \u_0_7._122_ ;
  wire \u_0_7._123_ ;
  wire \u_0_7._124_ ;
  wire \u_0_7._125_ ;
  wire \u_0_7._126_ ;
  wire \u_0_7._127_ ;
  wire \u_0_7._128_ ;
  wire \u_0_7._129_ ;
  wire \u_0_7._130_ ;
  wire \u_0_7._131_ ;
  wire \u_0_7._132_ ;
  wire \u_0_7._133_ ;
  wire \u_0_7._134_ ;
  wire \u_0_7.nC[0] ;
  wire \u_0_7.nC[8] ;
  wire \u_0_7.nCin ;
  wire \u_0_7.nCout ;
  wire \u_0_7.nG[-1] ;
  wire \u_0_7.nP[-1] ;
  wire \u_0_7.u_cla.A[0] ;
  wire \u_0_7.u_cla.A[1] ;
  wire \u_0_7.u_cla.A[2] ;
  wire \u_0_7.u_cla.A[3] ;
  wire \u_0_7.u_cla.A[4] ;
  wire \u_0_7.u_cla.A[5] ;
  wire \u_0_7.u_cla.A[6] ;
  wire \u_0_7.u_cla.A[7] ;
  wire \u_0_7.u_cla.B[0] ;
  wire \u_0_7.u_cla.B[1] ;
  wire \u_0_7.u_cla.B[2] ;
  wire \u_0_7.u_cla.B[3] ;
  wire \u_0_7.u_cla.B[4] ;
  wire \u_0_7.u_cla.B[5] ;
  wire \u_0_7.u_cla.B[6] ;
  wire \u_0_7.u_cla.B[7] ;
  wire \u_0_7.u_cla.genblk1.u_high.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.A[1] ;
  wire \u_0_7.u_cla.genblk1.u_high.A[2] ;
  wire \u_0_7.u_cla.genblk1.u_high.A[3] ;
  wire \u_0_7.u_cla.genblk1.u_high.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.B[1] ;
  wire \u_0_7.u_cla.genblk1.u_high.B[2] ;
  wire \u_0_7.u_cla.genblk1.u_high.B[3] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.A[1] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.B[1] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.A[1] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.B[1] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.A[1] ;
  wire \u_0_7.u_cla.genblk1.u_low.A[2] ;
  wire \u_0_7.u_cla.genblk1.u_low.A[3] ;
  wire \u_0_7.u_cla.genblk1.u_low.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.B[1] ;
  wire \u_0_7.u_cla.genblk1.u_low.B[2] ;
  wire \u_0_7.u_cla.genblk1.u_low.B[3] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.A[1] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.B[1] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.A[1] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.B[1] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_16_23.A[0] ;
  wire \u_16_23.A[1] ;
  wire \u_16_23.A[2] ;
  wire \u_16_23.A[3] ;
  wire \u_16_23.A[4] ;
  wire \u_16_23.A[5] ;
  wire \u_16_23.A[6] ;
  wire \u_16_23.A[7] ;
  wire \u_16_23.B[0] ;
  wire \u_16_23.B[1] ;
  wire \u_16_23.B[2] ;
  wire \u_16_23.B[3] ;
  wire \u_16_23.B[4] ;
  wire \u_16_23.B[5] ;
  wire \u_16_23.B[6] ;
  wire \u_16_23.B[7] ;
  wire \u_16_23.S[0] ;
  wire \u_16_23.S[1] ;
  wire \u_16_23.S[2] ;
  wire \u_16_23.S[3] ;
  wire \u_16_23.S[4] ;
  wire \u_16_23.S[5] ;
  wire \u_16_23.S[6] ;
  wire \u_16_23.S[7] ;
  wire \u_16_23._092_ ;
  wire \u_16_23._093_ ;
  wire \u_16_23._094_ ;
  wire \u_16_23._095_ ;
  wire \u_16_23._096_ ;
  wire \u_16_23._097_ ;
  wire \u_16_23._098_ ;
  wire \u_16_23._099_ ;
  wire \u_16_23._101_ ;
  wire \u_16_23._102_ ;
  wire \u_16_23._103_ ;
  wire \u_16_23._104_ ;
  wire \u_16_23._105_ ;
  wire \u_16_23._106_ ;
  wire \u_16_23._107_ ;
  wire \u_16_23._108_ ;
  wire \u_16_23._109_ ;
  wire \u_16_23._110_ ;
  wire \u_16_23._111_ ;
  wire \u_16_23._112_ ;
  wire \u_16_23._113_ ;
  wire \u_16_23._114_ ;
  wire \u_16_23._115_ ;
  wire \u_16_23._116_ ;
  wire \u_16_23._117_ ;
  wire \u_16_23._118_ ;
  wire \u_16_23._119_ ;
  wire \u_16_23._120_ ;
  wire \u_16_23._121_ ;
  wire \u_16_23._122_ ;
  wire \u_16_23._123_ ;
  wire \u_16_23._124_ ;
  wire \u_16_23._125_ ;
  wire \u_16_23._126_ ;
  wire \u_16_23._127_ ;
  wire \u_16_23._128_ ;
  wire \u_16_23._129_ ;
  wire \u_16_23._130_ ;
  wire \u_16_23._131_ ;
  wire \u_16_23._132_ ;
  wire \u_16_23._133_ ;
  wire \u_16_23._134_ ;
  wire \u_16_23.nC[0] ;
  wire \u_16_23.nC[8] ;
  wire \u_16_23.nCin ;
  wire \u_16_23.nCout ;
  wire \u_16_23.nG[-1] ;
  wire \u_16_23.nP[-1] ;
  wire \u_16_23.u_cla.A[0] ;
  wire \u_16_23.u_cla.A[1] ;
  wire \u_16_23.u_cla.A[2] ;
  wire \u_16_23.u_cla.A[3] ;
  wire \u_16_23.u_cla.A[4] ;
  wire \u_16_23.u_cla.A[5] ;
  wire \u_16_23.u_cla.A[6] ;
  wire \u_16_23.u_cla.A[7] ;
  wire \u_16_23.u_cla.B[0] ;
  wire \u_16_23.u_cla.B[1] ;
  wire \u_16_23.u_cla.B[2] ;
  wire \u_16_23.u_cla.B[3] ;
  wire \u_16_23.u_cla.B[4] ;
  wire \u_16_23.u_cla.B[5] ;
  wire \u_16_23.u_cla.B[6] ;
  wire \u_16_23.u_cla.B[7] ;
  wire \u_16_23.u_cla.genblk1.u_high.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.A[1] ;
  wire \u_16_23.u_cla.genblk1.u_high.A[2] ;
  wire \u_16_23.u_cla.genblk1.u_high.A[3] ;
  wire \u_16_23.u_cla.genblk1.u_high.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.B[1] ;
  wire \u_16_23.u_cla.genblk1.u_high.B[2] ;
  wire \u_16_23.u_cla.genblk1.u_high.B[3] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.A[1] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.B[1] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.A[1] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.B[1] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.A[1] ;
  wire \u_16_23.u_cla.genblk1.u_low.A[2] ;
  wire \u_16_23.u_cla.genblk1.u_low.A[3] ;
  wire \u_16_23.u_cla.genblk1.u_low.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.B[1] ;
  wire \u_16_23.u_cla.genblk1.u_low.B[2] ;
  wire \u_16_23.u_cla.genblk1.u_low.B[3] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.A[1] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.B[1] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.A[1] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.B[1] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_24_31.A[0] ;
  wire \u_24_31.A[1] ;
  wire \u_24_31.A[2] ;
  wire \u_24_31.A[3] ;
  wire \u_24_31.A[4] ;
  wire \u_24_31.A[5] ;
  wire \u_24_31.A[6] ;
  wire \u_24_31.A[7] ;
  wire \u_24_31.B[0] ;
  wire \u_24_31.B[1] ;
  wire \u_24_31.B[2] ;
  wire \u_24_31.B[3] ;
  wire \u_24_31.B[4] ;
  wire \u_24_31.B[5] ;
  wire \u_24_31.B[6] ;
  wire \u_24_31.B[7] ;
  wire \u_24_31.S[0] ;
  wire \u_24_31.S[1] ;
  wire \u_24_31.S[2] ;
  wire \u_24_31.S[3] ;
  wire \u_24_31.S[4] ;
  wire \u_24_31.S[5] ;
  wire \u_24_31.S[6] ;
  wire \u_24_31.S[7] ;
  wire \u_24_31._092_ ;
  wire \u_24_31._093_ ;
  wire \u_24_31._094_ ;
  wire \u_24_31._095_ ;
  wire \u_24_31._096_ ;
  wire \u_24_31._097_ ;
  wire \u_24_31._098_ ;
  wire \u_24_31._099_ ;
  wire \u_24_31._101_ ;
  wire \u_24_31._102_ ;
  wire \u_24_31._103_ ;
  wire \u_24_31._104_ ;
  wire \u_24_31._105_ ;
  wire \u_24_31._106_ ;
  wire \u_24_31._107_ ;
  wire \u_24_31._108_ ;
  wire \u_24_31._109_ ;
  wire \u_24_31._110_ ;
  wire \u_24_31._111_ ;
  wire \u_24_31._112_ ;
  wire \u_24_31._113_ ;
  wire \u_24_31._114_ ;
  wire \u_24_31._115_ ;
  wire \u_24_31._116_ ;
  wire \u_24_31._117_ ;
  wire \u_24_31._118_ ;
  wire \u_24_31._119_ ;
  wire \u_24_31._120_ ;
  wire \u_24_31._121_ ;
  wire \u_24_31._122_ ;
  wire \u_24_31._123_ ;
  wire \u_24_31._124_ ;
  wire \u_24_31._125_ ;
  wire \u_24_31._126_ ;
  wire \u_24_31._127_ ;
  wire \u_24_31._128_ ;
  wire \u_24_31._129_ ;
  wire \u_24_31._130_ ;
  wire \u_24_31._131_ ;
  wire \u_24_31._132_ ;
  wire \u_24_31._133_ ;
  wire \u_24_31._134_ ;
  wire \u_24_31.nC[0] ;
  wire \u_24_31.nC[8] ;
  wire \u_24_31.nCin ;
  wire \u_24_31.nCout ;
  wire \u_24_31.nG[-1] ;
  wire \u_24_31.nP[-1] ;
  wire \u_24_31.u_cla.A[0] ;
  wire \u_24_31.u_cla.A[1] ;
  wire \u_24_31.u_cla.A[2] ;
  wire \u_24_31.u_cla.A[3] ;
  wire \u_24_31.u_cla.A[4] ;
  wire \u_24_31.u_cla.A[5] ;
  wire \u_24_31.u_cla.A[6] ;
  wire \u_24_31.u_cla.A[7] ;
  wire \u_24_31.u_cla.B[0] ;
  wire \u_24_31.u_cla.B[1] ;
  wire \u_24_31.u_cla.B[2] ;
  wire \u_24_31.u_cla.B[3] ;
  wire \u_24_31.u_cla.B[4] ;
  wire \u_24_31.u_cla.B[5] ;
  wire \u_24_31.u_cla.B[6] ;
  wire \u_24_31.u_cla.B[7] ;
  wire \u_24_31.u_cla.genblk1.u_high.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.A[1] ;
  wire \u_24_31.u_cla.genblk1.u_high.A[2] ;
  wire \u_24_31.u_cla.genblk1.u_high.A[3] ;
  wire \u_24_31.u_cla.genblk1.u_high.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.B[1] ;
  wire \u_24_31.u_cla.genblk1.u_high.B[2] ;
  wire \u_24_31.u_cla.genblk1.u_high.B[3] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.A[1] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.B[1] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.A[1] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.B[1] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.A[1] ;
  wire \u_24_31.u_cla.genblk1.u_low.A[2] ;
  wire \u_24_31.u_cla.genblk1.u_low.A[3] ;
  wire \u_24_31.u_cla.genblk1.u_low.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.B[1] ;
  wire \u_24_31.u_cla.genblk1.u_low.B[2] ;
  wire \u_24_31.u_cla.genblk1.u_low.B[3] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.A[1] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.B[1] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.A[1] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.B[1] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_8_15.A[0] ;
  wire \u_8_15.A[1] ;
  wire \u_8_15.A[2] ;
  wire \u_8_15.A[3] ;
  wire \u_8_15.A[4] ;
  wire \u_8_15.A[5] ;
  wire \u_8_15.A[6] ;
  wire \u_8_15.A[7] ;
  wire \u_8_15.B[0] ;
  wire \u_8_15.B[1] ;
  wire \u_8_15.B[2] ;
  wire \u_8_15.B[3] ;
  wire \u_8_15.B[4] ;
  wire \u_8_15.B[5] ;
  wire \u_8_15.B[6] ;
  wire \u_8_15.B[7] ;
  wire \u_8_15.S[0] ;
  wire \u_8_15.S[1] ;
  wire \u_8_15.S[2] ;
  wire \u_8_15.S[3] ;
  wire \u_8_15.S[4] ;
  wire \u_8_15.S[5] ;
  wire \u_8_15.S[6] ;
  wire \u_8_15.S[7] ;
  wire \u_8_15._092_ ;
  wire \u_8_15._093_ ;
  wire \u_8_15._094_ ;
  wire \u_8_15._095_ ;
  wire \u_8_15._096_ ;
  wire \u_8_15._097_ ;
  wire \u_8_15._098_ ;
  wire \u_8_15._099_ ;
  wire \u_8_15._101_ ;
  wire \u_8_15._102_ ;
  wire \u_8_15._103_ ;
  wire \u_8_15._104_ ;
  wire \u_8_15._105_ ;
  wire \u_8_15._106_ ;
  wire \u_8_15._107_ ;
  wire \u_8_15._108_ ;
  wire \u_8_15._109_ ;
  wire \u_8_15._110_ ;
  wire \u_8_15._111_ ;
  wire \u_8_15._112_ ;
  wire \u_8_15._113_ ;
  wire \u_8_15._114_ ;
  wire \u_8_15._115_ ;
  wire \u_8_15._116_ ;
  wire \u_8_15._117_ ;
  wire \u_8_15._118_ ;
  wire \u_8_15._119_ ;
  wire \u_8_15._120_ ;
  wire \u_8_15._121_ ;
  wire \u_8_15._122_ ;
  wire \u_8_15._123_ ;
  wire \u_8_15._124_ ;
  wire \u_8_15._125_ ;
  wire \u_8_15._126_ ;
  wire \u_8_15._127_ ;
  wire \u_8_15._128_ ;
  wire \u_8_15._129_ ;
  wire \u_8_15._130_ ;
  wire \u_8_15._131_ ;
  wire \u_8_15._132_ ;
  wire \u_8_15._133_ ;
  wire \u_8_15._134_ ;
  wire \u_8_15.nC[0] ;
  wire \u_8_15.nC[8] ;
  wire \u_8_15.nCin ;
  wire \u_8_15.nCout ;
  wire \u_8_15.nG[-1] ;
  wire \u_8_15.nP[-1] ;
  wire \u_8_15.u_cla.A[0] ;
  wire \u_8_15.u_cla.A[1] ;
  wire \u_8_15.u_cla.A[2] ;
  wire \u_8_15.u_cla.A[3] ;
  wire \u_8_15.u_cla.A[4] ;
  wire \u_8_15.u_cla.A[5] ;
  wire \u_8_15.u_cla.A[6] ;
  wire \u_8_15.u_cla.A[7] ;
  wire \u_8_15.u_cla.B[0] ;
  wire \u_8_15.u_cla.B[1] ;
  wire \u_8_15.u_cla.B[2] ;
  wire \u_8_15.u_cla.B[3] ;
  wire \u_8_15.u_cla.B[4] ;
  wire \u_8_15.u_cla.B[5] ;
  wire \u_8_15.u_cla.B[6] ;
  wire \u_8_15.u_cla.B[7] ;
  wire \u_8_15.u_cla.genblk1.u_high.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.A[1] ;
  wire \u_8_15.u_cla.genblk1.u_high.A[2] ;
  wire \u_8_15.u_cla.genblk1.u_high.A[3] ;
  wire \u_8_15.u_cla.genblk1.u_high.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.B[1] ;
  wire \u_8_15.u_cla.genblk1.u_high.B[2] ;
  wire \u_8_15.u_cla.genblk1.u_high.B[3] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.A[1] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.B[1] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.A[1] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.B[1] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.A[1] ;
  wire \u_8_15.u_cla.genblk1.u_low.A[2] ;
  wire \u_8_15.u_cla.genblk1.u_low.A[3] ;
  wire \u_8_15.u_cla.genblk1.u_low.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.B[1] ;
  wire \u_8_15.u_cla.genblk1.u_low.B[2] ;
  wire \u_8_15.u_cla.genblk1.u_low.B[3] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.A[1] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.B[1] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.A[1] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.B[1] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0] ;
  NOT \u_0_7._135_  (
    .A(A[7]),
    .Y(\u_0_7._102_ )
  );
  NOT \u_0_7._136_  (
    .A(B[7]),
    .Y(\u_0_7._103_ )
  );
  AND2 \u_0_7._137_  (
    .A1(A[6]),
    .A2(B[6]),
    .Y(\u_0_7._104_ )
  );
  NOR2 \u_0_7._138_  (
    .A1(A[6]),
    .A2(B[6]),
    .Y(\u_0_7._105_ )
  );
  OR2 \u_0_7._139_  (
    .A1(A[6]),
    .A2(B[6]),
    .Y(\u_0_7._106_ )
  );
  AND2 \u_0_7._140_  (
    .A1(A[5]),
    .A2(B[5]),
    .Y(\u_0_7._107_ )
  );
  NOR2 \u_0_7._141_  (
    .A1(A[5]),
    .A2(B[5]),
    .Y(\u_0_7._108_ )
  );
  AND2 \u_0_7._142_  (
    .A1(A[4]),
    .A2(B[4]),
    .Y(\u_0_7._109_ )
  );
  NOT \u_0_7._143_  (
    .A(\u_0_7._109_ ),
    .Y(\u_0_7._110_ )
  );
  NOR2 \u_0_7._144_  (
    .A1(A[4]),
    .A2(B[4]),
    .Y(\u_0_7._111_ )
  );
  NAND2 \u_0_7._145_  (
    .A1(A[3]),
    .A2(B[3]),
    .Y(\u_0_7._112_ )
  );
  NAND2 \u_0_7._146_  (
    .A1(A[2]),
    .A2(B[2]),
    .Y(\u_0_7._113_ )
  );
  NOT \u_0_7._147_  (
    .A(\u_0_7._113_ ),
    .Y(\u_0_7._114_ )
  );
  OR2 \u_0_7._148_  (
    .A1(A[2]),
    .A2(B[2]),
    .Y(\u_0_7._115_ )
  );
  NOR2 \u_0_7._149_  (
    .A1(A[0]),
    .A2(B[0]),
    .Y(\u_0_7._116_ )
  );
  NAND2 \u_0_7._150_  (
    .A1(A[0]),
    .A2(B[0]),
    .Y(\u_0_7._117_ )
  );
  OAI21 \u_0_7._151_  (
    .A(\u_0_7._117_ ),
    .B1(\u_0_7._116_ ),
    .B2(1'h1),
    .Y(\u_0_7._118_ )
  );
  MAJ3 \u_0_7._152_  (
    .A1(A[1]),
    .A2(B[1]),
    .A3(\u_0_7._118_ ),
    .Y(\u_0_7._119_ )
  );
  OA21 \u_0_7._153_  (
    .A(\u_0_7._115_ ),
    .B1(\u_0_7._119_ ),
    .B2(\u_0_7._114_ ),
    .Y(\u_0_7._120_ )
  );
  OAI221 \u_0_7._154_  (
    .A1(A[3]),
    .A2(B[3]),
    .B1(\u_0_7._114_ ),
    .B2(\u_0_7._119_ ),
    .C(\u_0_7._115_ ),
    .Y(\u_0_7._121_ )
  );
  NAND2 \u_0_7._155_  (
    .A1(\u_0_7._112_ ),
    .A2(\u_0_7._121_ ),
    .Y(\u_0_7._122_ )
  );
  MAJ3 \u_0_7._156_  (
    .A1(A[4]),
    .A2(B[4]),
    .A3(\u_0_7._122_ ),
    .Y(\u_0_7._123_ )
  );
  AOI311 \u_0_7._157_  (
    .A1(\u_0_7._110_ ),
    .A2(\u_0_7._112_ ),
    .A3(\u_0_7._121_ ),
    .B1(\u_0_7._111_ ),
    .C1(\u_0_7._108_ ),
    .Y(\u_0_7._124_ )
  );
  NOR2 \u_0_7._158_  (
    .A1(\u_0_7._107_ ),
    .A2(\u_0_7._124_ ),
    .Y(\u_0_7._125_ )
  );
  OAI31 \u_0_7._159_  (
    .A1(\u_0_7._104_ ),
    .A2(\u_0_7._107_ ),
    .A3(\u_0_7._124_ ),
    .B(\u_0_7._106_ ),
    .Y(\u_0_7._126_ )
  );
  MAJ3 \u_0_7._160_  (
    .A1(\u_0_7._102_ ),
    .A2(\u_0_7._103_ ),
    .A3(\u_0_7._126_ ),
    .Y(\u_0_7._101_ )
  );
  OR2 \u_0_7._161_  (
    .A1(1'h1),
    .A2(\u_0_7._117_ ),
    .Y(\u_0_7._127_ )
  );
  AOI22 \u_0_7._162_  (
    .A1(1'h1),
    .A2(\u_0_7._116_ ),
    .B1(\u_0_7._118_ ),
    .B2(\u_0_7._127_ ),
    .Y(\u_0_7._092_ )
  );
  XOR2 \u_0_7._163_  (
    .A(A[1]),
    .B(B[1]),
    .Y(\u_0_7._128_ )
  );
  XOR2 \u_0_7._164_  (
    .A(\u_0_7._118_ ),
    .B(\u_0_7._128_ ),
    .Y(\u_0_7._093_ )
  );
  NAND2 \u_0_7._165_  (
    .A1(\u_0_7._113_ ),
    .A2(\u_0_7._115_ ),
    .Y(\u_0_7._129_ )
  );
  XNOR2 \u_0_7._166_  (
    .A(\u_0_7._119_ ),
    .B(\u_0_7._129_ ),
    .Y(\u_0_7._094_ )
  );
  XNOR2 \u_0_7._167_  (
    .A(A[3]),
    .B(B[3]),
    .Y(\u_0_7._130_ )
  );
  XNOR2 \u_0_7._168_  (
    .A(\u_0_7._120_ ),
    .B(\u_0_7._130_ ),
    .Y(\u_0_7._095_ )
  );
  NOR2 \u_0_7._169_  (
    .A1(\u_0_7._109_ ),
    .A2(\u_0_7._111_ ),
    .Y(\u_0_7._131_ )
  );
  XOR2 \u_0_7._170_  (
    .A(\u_0_7._122_ ),
    .B(\u_0_7._131_ ),
    .Y(\u_0_7._096_ )
  );
  NOR2 \u_0_7._171_  (
    .A1(\u_0_7._107_ ),
    .A2(\u_0_7._108_ ),
    .Y(\u_0_7._132_ )
  );
  XOR2 \u_0_7._172_  (
    .A(\u_0_7._123_ ),
    .B(\u_0_7._132_ ),
    .Y(\u_0_7._097_ )
  );
  NOR2 \u_0_7._173_  (
    .A1(\u_0_7._104_ ),
    .A2(\u_0_7._105_ ),
    .Y(\u_0_7._133_ )
  );
  XNOR2 \u_0_7._174_  (
    .A(\u_0_7._125_ ),
    .B(\u_0_7._133_ ),
    .Y(\u_0_7._098_ )
  );
  XNOR2 \u_0_7._175_  (
    .A(A[7]),
    .B(B[7]),
    .Y(\u_0_7._134_ )
  );
  XOR2 \u_0_7._176_  (
    .A(\u_0_7._126_ ),
    .B(\u_0_7._134_ ),
    .Y(\u_0_7._099_ )
  );
  NOT \u_16_23._135_  (
    .A(A[23]),
    .Y(\u_16_23._102_ )
  );
  NOT \u_16_23._136_  (
    .A(B[23]),
    .Y(\u_16_23._103_ )
  );
  AND2 \u_16_23._137_  (
    .A1(A[22]),
    .A2(B[22]),
    .Y(\u_16_23._104_ )
  );
  NOR2 \u_16_23._138_  (
    .A1(A[22]),
    .A2(B[22]),
    .Y(\u_16_23._105_ )
  );
  OR2 \u_16_23._139_  (
    .A1(A[22]),
    .A2(B[22]),
    .Y(\u_16_23._106_ )
  );
  AND2 \u_16_23._140_  (
    .A1(A[21]),
    .A2(B[21]),
    .Y(\u_16_23._107_ )
  );
  NOR2 \u_16_23._141_  (
    .A1(A[21]),
    .A2(B[21]),
    .Y(\u_16_23._108_ )
  );
  AND2 \u_16_23._142_  (
    .A1(A[20]),
    .A2(B[20]),
    .Y(\u_16_23._109_ )
  );
  NOT \u_16_23._143_  (
    .A(\u_16_23._109_ ),
    .Y(\u_16_23._110_ )
  );
  NOR2 \u_16_23._144_  (
    .A1(A[20]),
    .A2(B[20]),
    .Y(\u_16_23._111_ )
  );
  NAND2 \u_16_23._145_  (
    .A1(A[19]),
    .A2(B[19]),
    .Y(\u_16_23._112_ )
  );
  NAND2 \u_16_23._146_  (
    .A1(A[18]),
    .A2(B[18]),
    .Y(\u_16_23._113_ )
  );
  NOT \u_16_23._147_  (
    .A(\u_16_23._113_ ),
    .Y(\u_16_23._114_ )
  );
  OR2 \u_16_23._148_  (
    .A1(A[18]),
    .A2(B[18]),
    .Y(\u_16_23._115_ )
  );
  NOR2 \u_16_23._149_  (
    .A1(A[16]),
    .A2(B[16]),
    .Y(\u_16_23._116_ )
  );
  NAND2 \u_16_23._150_  (
    .A1(A[16]),
    .A2(B[16]),
    .Y(\u_16_23._117_ )
  );
  OAI21 \u_16_23._151_  (
    .A(\u_16_23._117_ ),
    .B1(\u_16_23._116_ ),
    .B2(\u_16_23.nCin ),
    .Y(\u_16_23._118_ )
  );
  MAJ3 \u_16_23._152_  (
    .A1(A[17]),
    .A2(B[17]),
    .A3(\u_16_23._118_ ),
    .Y(\u_16_23._119_ )
  );
  OA21 \u_16_23._153_  (
    .A(\u_16_23._115_ ),
    .B1(\u_16_23._119_ ),
    .B2(\u_16_23._114_ ),
    .Y(\u_16_23._120_ )
  );
  OAI221 \u_16_23._154_  (
    .A1(A[19]),
    .A2(B[19]),
    .B1(\u_16_23._114_ ),
    .B2(\u_16_23._119_ ),
    .C(\u_16_23._115_ ),
    .Y(\u_16_23._121_ )
  );
  NAND2 \u_16_23._155_  (
    .A1(\u_16_23._112_ ),
    .A2(\u_16_23._121_ ),
    .Y(\u_16_23._122_ )
  );
  MAJ3 \u_16_23._156_  (
    .A1(A[20]),
    .A2(B[20]),
    .A3(\u_16_23._122_ ),
    .Y(\u_16_23._123_ )
  );
  AOI311 \u_16_23._157_  (
    .A1(\u_16_23._110_ ),
    .A2(\u_16_23._112_ ),
    .A3(\u_16_23._121_ ),
    .B1(\u_16_23._111_ ),
    .C1(\u_16_23._108_ ),
    .Y(\u_16_23._124_ )
  );
  NOR2 \u_16_23._158_  (
    .A1(\u_16_23._107_ ),
    .A2(\u_16_23._124_ ),
    .Y(\u_16_23._125_ )
  );
  OAI31 \u_16_23._159_  (
    .A1(\u_16_23._104_ ),
    .A2(\u_16_23._107_ ),
    .A3(\u_16_23._124_ ),
    .B(\u_16_23._106_ ),
    .Y(\u_16_23._126_ )
  );
  MAJ3 \u_16_23._160_  (
    .A1(\u_16_23._102_ ),
    .A2(\u_16_23._103_ ),
    .A3(\u_16_23._126_ ),
    .Y(\u_16_23._101_ )
  );
  OR2 \u_16_23._161_  (
    .A1(\u_16_23.nCin ),
    .A2(\u_16_23._117_ ),
    .Y(\u_16_23._127_ )
  );
  AOI22 \u_16_23._162_  (
    .A1(\u_16_23.nCin ),
    .A2(\u_16_23._116_ ),
    .B1(\u_16_23._118_ ),
    .B2(\u_16_23._127_ ),
    .Y(\u_16_23._092_ )
  );
  XOR2 \u_16_23._163_  (
    .A(A[17]),
    .B(B[17]),
    .Y(\u_16_23._128_ )
  );
  XOR2 \u_16_23._164_  (
    .A(\u_16_23._118_ ),
    .B(\u_16_23._128_ ),
    .Y(\u_16_23._093_ )
  );
  NAND2 \u_16_23._165_  (
    .A1(\u_16_23._113_ ),
    .A2(\u_16_23._115_ ),
    .Y(\u_16_23._129_ )
  );
  XNOR2 \u_16_23._166_  (
    .A(\u_16_23._119_ ),
    .B(\u_16_23._129_ ),
    .Y(\u_16_23._094_ )
  );
  XNOR2 \u_16_23._167_  (
    .A(A[19]),
    .B(B[19]),
    .Y(\u_16_23._130_ )
  );
  XNOR2 \u_16_23._168_  (
    .A(\u_16_23._120_ ),
    .B(\u_16_23._130_ ),
    .Y(\u_16_23._095_ )
  );
  NOR2 \u_16_23._169_  (
    .A1(\u_16_23._109_ ),
    .A2(\u_16_23._111_ ),
    .Y(\u_16_23._131_ )
  );
  XOR2 \u_16_23._170_  (
    .A(\u_16_23._122_ ),
    .B(\u_16_23._131_ ),
    .Y(\u_16_23._096_ )
  );
  NOR2 \u_16_23._171_  (
    .A1(\u_16_23._107_ ),
    .A2(\u_16_23._108_ ),
    .Y(\u_16_23._132_ )
  );
  XOR2 \u_16_23._172_  (
    .A(\u_16_23._123_ ),
    .B(\u_16_23._132_ ),
    .Y(\u_16_23._097_ )
  );
  NOR2 \u_16_23._173_  (
    .A1(\u_16_23._104_ ),
    .A2(\u_16_23._105_ ),
    .Y(\u_16_23._133_ )
  );
  XNOR2 \u_16_23._174_  (
    .A(\u_16_23._125_ ),
    .B(\u_16_23._133_ ),
    .Y(\u_16_23._098_ )
  );
  XNOR2 \u_16_23._175_  (
    .A(A[23]),
    .B(B[23]),
    .Y(\u_16_23._134_ )
  );
  XOR2 \u_16_23._176_  (
    .A(\u_16_23._126_ ),
    .B(\u_16_23._134_ ),
    .Y(\u_16_23._099_ )
  );
  NOT \u_24_31._135_  (
    .A(A[31]),
    .Y(\u_24_31._102_ )
  );
  NOT \u_24_31._136_  (
    .A(B[31]),
    .Y(\u_24_31._103_ )
  );
  AND2 \u_24_31._137_  (
    .A1(A[30]),
    .A2(B[30]),
    .Y(\u_24_31._104_ )
  );
  NOR2 \u_24_31._138_  (
    .A1(A[30]),
    .A2(B[30]),
    .Y(\u_24_31._105_ )
  );
  OR2 \u_24_31._139_  (
    .A1(A[30]),
    .A2(B[30]),
    .Y(\u_24_31._106_ )
  );
  AND2 \u_24_31._140_  (
    .A1(A[29]),
    .A2(B[29]),
    .Y(\u_24_31._107_ )
  );
  NOR2 \u_24_31._141_  (
    .A1(A[29]),
    .A2(B[29]),
    .Y(\u_24_31._108_ )
  );
  AND2 \u_24_31._142_  (
    .A1(A[28]),
    .A2(B[28]),
    .Y(\u_24_31._109_ )
  );
  NOT \u_24_31._143_  (
    .A(\u_24_31._109_ ),
    .Y(\u_24_31._110_ )
  );
  NOR2 \u_24_31._144_  (
    .A1(A[28]),
    .A2(B[28]),
    .Y(\u_24_31._111_ )
  );
  NAND2 \u_24_31._145_  (
    .A1(A[27]),
    .A2(B[27]),
    .Y(\u_24_31._112_ )
  );
  NAND2 \u_24_31._146_  (
    .A1(A[26]),
    .A2(B[26]),
    .Y(\u_24_31._113_ )
  );
  NOT \u_24_31._147_  (
    .A(\u_24_31._113_ ),
    .Y(\u_24_31._114_ )
  );
  OR2 \u_24_31._148_  (
    .A1(A[26]),
    .A2(B[26]),
    .Y(\u_24_31._115_ )
  );
  NOR2 \u_24_31._149_  (
    .A1(A[24]),
    .A2(B[24]),
    .Y(\u_24_31._116_ )
  );
  NAND2 \u_24_31._150_  (
    .A1(A[24]),
    .A2(B[24]),
    .Y(\u_24_31._117_ )
  );
  OAI21 \u_24_31._151_  (
    .A(\u_24_31._117_ ),
    .B1(\u_24_31._116_ ),
    .B2(\u_16_23._101_ ),
    .Y(\u_24_31._118_ )
  );
  MAJ3 \u_24_31._152_  (
    .A1(A[25]),
    .A2(B[25]),
    .A3(\u_24_31._118_ ),
    .Y(\u_24_31._119_ )
  );
  OA21 \u_24_31._153_  (
    .A(\u_24_31._115_ ),
    .B1(\u_24_31._119_ ),
    .B2(\u_24_31._114_ ),
    .Y(\u_24_31._120_ )
  );
  OAI221 \u_24_31._154_  (
    .A1(A[27]),
    .A2(B[27]),
    .B1(\u_24_31._114_ ),
    .B2(\u_24_31._119_ ),
    .C(\u_24_31._115_ ),
    .Y(\u_24_31._121_ )
  );
  NAND2 \u_24_31._155_  (
    .A1(\u_24_31._112_ ),
    .A2(\u_24_31._121_ ),
    .Y(\u_24_31._122_ )
  );
  MAJ3 \u_24_31._156_  (
    .A1(A[28]),
    .A2(B[28]),
    .A3(\u_24_31._122_ ),
    .Y(\u_24_31._123_ )
  );
  AOI311 \u_24_31._157_  (
    .A1(\u_24_31._110_ ),
    .A2(\u_24_31._112_ ),
    .A3(\u_24_31._121_ ),
    .B1(\u_24_31._111_ ),
    .C1(\u_24_31._108_ ),
    .Y(\u_24_31._124_ )
  );
  NOR2 \u_24_31._158_  (
    .A1(\u_24_31._107_ ),
    .A2(\u_24_31._124_ ),
    .Y(\u_24_31._125_ )
  );
  OAI31 \u_24_31._159_  (
    .A1(\u_24_31._104_ ),
    .A2(\u_24_31._107_ ),
    .A3(\u_24_31._124_ ),
    .B(\u_24_31._106_ ),
    .Y(\u_24_31._126_ )
  );
  MAJ3 \u_24_31._160_  (
    .A1(\u_24_31._102_ ),
    .A2(\u_24_31._103_ ),
    .A3(\u_24_31._126_ ),
    .Y(\u_24_31._101_ )
  );
  OR2 \u_24_31._161_  (
    .A1(\u_16_23._101_ ),
    .A2(\u_24_31._117_ ),
    .Y(\u_24_31._127_ )
  );
  AOI22 \u_24_31._162_  (
    .A1(\u_16_23._101_ ),
    .A2(\u_24_31._116_ ),
    .B1(\u_24_31._118_ ),
    .B2(\u_24_31._127_ ),
    .Y(\u_24_31._092_ )
  );
  XOR2 \u_24_31._163_  (
    .A(A[25]),
    .B(B[25]),
    .Y(\u_24_31._128_ )
  );
  XOR2 \u_24_31._164_  (
    .A(\u_24_31._118_ ),
    .B(\u_24_31._128_ ),
    .Y(\u_24_31._093_ )
  );
  NAND2 \u_24_31._165_  (
    .A1(\u_24_31._113_ ),
    .A2(\u_24_31._115_ ),
    .Y(\u_24_31._129_ )
  );
  XNOR2 \u_24_31._166_  (
    .A(\u_24_31._119_ ),
    .B(\u_24_31._129_ ),
    .Y(\u_24_31._094_ )
  );
  XNOR2 \u_24_31._167_  (
    .A(A[27]),
    .B(B[27]),
    .Y(\u_24_31._130_ )
  );
  XNOR2 \u_24_31._168_  (
    .A(\u_24_31._120_ ),
    .B(\u_24_31._130_ ),
    .Y(\u_24_31._095_ )
  );
  NOR2 \u_24_31._169_  (
    .A1(\u_24_31._109_ ),
    .A2(\u_24_31._111_ ),
    .Y(\u_24_31._131_ )
  );
  XOR2 \u_24_31._170_  (
    .A(\u_24_31._122_ ),
    .B(\u_24_31._131_ ),
    .Y(\u_24_31._096_ )
  );
  NOR2 \u_24_31._171_  (
    .A1(\u_24_31._107_ ),
    .A2(\u_24_31._108_ ),
    .Y(\u_24_31._132_ )
  );
  XOR2 \u_24_31._172_  (
    .A(\u_24_31._123_ ),
    .B(\u_24_31._132_ ),
    .Y(\u_24_31._097_ )
  );
  NOR2 \u_24_31._173_  (
    .A1(\u_24_31._104_ ),
    .A2(\u_24_31._105_ ),
    .Y(\u_24_31._133_ )
  );
  XNOR2 \u_24_31._174_  (
    .A(\u_24_31._125_ ),
    .B(\u_24_31._133_ ),
    .Y(\u_24_31._098_ )
  );
  XNOR2 \u_24_31._175_  (
    .A(A[31]),
    .B(B[31]),
    .Y(\u_24_31._134_ )
  );
  XOR2 \u_24_31._176_  (
    .A(\u_24_31._126_ ),
    .B(\u_24_31._134_ ),
    .Y(\u_24_31._099_ )
  );
  NOT \u_8_15._135_  (
    .A(A[15]),
    .Y(\u_8_15._102_ )
  );
  NOT \u_8_15._136_  (
    .A(B[15]),
    .Y(\u_8_15._103_ )
  );
  AND2 \u_8_15._137_  (
    .A1(A[14]),
    .A2(B[14]),
    .Y(\u_8_15._104_ )
  );
  NOR2 \u_8_15._138_  (
    .A1(A[14]),
    .A2(B[14]),
    .Y(\u_8_15._105_ )
  );
  OR2 \u_8_15._139_  (
    .A1(A[14]),
    .A2(B[14]),
    .Y(\u_8_15._106_ )
  );
  AND2 \u_8_15._140_  (
    .A1(A[13]),
    .A2(B[13]),
    .Y(\u_8_15._107_ )
  );
  NOR2 \u_8_15._141_  (
    .A1(A[13]),
    .A2(B[13]),
    .Y(\u_8_15._108_ )
  );
  AND2 \u_8_15._142_  (
    .A1(A[12]),
    .A2(B[12]),
    .Y(\u_8_15._109_ )
  );
  NOT \u_8_15._143_  (
    .A(\u_8_15._109_ ),
    .Y(\u_8_15._110_ )
  );
  NOR2 \u_8_15._144_  (
    .A1(A[12]),
    .A2(B[12]),
    .Y(\u_8_15._111_ )
  );
  NAND2 \u_8_15._145_  (
    .A1(A[11]),
    .A2(B[11]),
    .Y(\u_8_15._112_ )
  );
  NAND2 \u_8_15._146_  (
    .A1(A[10]),
    .A2(B[10]),
    .Y(\u_8_15._113_ )
  );
  NOT \u_8_15._147_  (
    .A(\u_8_15._113_ ),
    .Y(\u_8_15._114_ )
  );
  OR2 \u_8_15._148_  (
    .A1(A[10]),
    .A2(B[10]),
    .Y(\u_8_15._115_ )
  );
  NOR2 \u_8_15._149_  (
    .A1(A[8]),
    .A2(B[8]),
    .Y(\u_8_15._116_ )
  );
  NAND2 \u_8_15._150_  (
    .A1(A[8]),
    .A2(B[8]),
    .Y(\u_8_15._117_ )
  );
  OAI21 \u_8_15._151_  (
    .A(\u_8_15._117_ ),
    .B1(\u_8_15._116_ ),
    .B2(\u_0_7._101_ ),
    .Y(\u_8_15._118_ )
  );
  MAJ3 \u_8_15._152_  (
    .A1(A[9]),
    .A2(B[9]),
    .A3(\u_8_15._118_ ),
    .Y(\u_8_15._119_ )
  );
  OA21 \u_8_15._153_  (
    .A(\u_8_15._115_ ),
    .B1(\u_8_15._119_ ),
    .B2(\u_8_15._114_ ),
    .Y(\u_8_15._120_ )
  );
  OAI221 \u_8_15._154_  (
    .A1(A[11]),
    .A2(B[11]),
    .B1(\u_8_15._114_ ),
    .B2(\u_8_15._119_ ),
    .C(\u_8_15._115_ ),
    .Y(\u_8_15._121_ )
  );
  NAND2 \u_8_15._155_  (
    .A1(\u_8_15._112_ ),
    .A2(\u_8_15._121_ ),
    .Y(\u_8_15._122_ )
  );
  MAJ3 \u_8_15._156_  (
    .A1(A[12]),
    .A2(B[12]),
    .A3(\u_8_15._122_ ),
    .Y(\u_8_15._123_ )
  );
  AOI311 \u_8_15._157_  (
    .A1(\u_8_15._110_ ),
    .A2(\u_8_15._112_ ),
    .A3(\u_8_15._121_ ),
    .B1(\u_8_15._111_ ),
    .C1(\u_8_15._108_ ),
    .Y(\u_8_15._124_ )
  );
  NOR2 \u_8_15._158_  (
    .A1(\u_8_15._107_ ),
    .A2(\u_8_15._124_ ),
    .Y(\u_8_15._125_ )
  );
  OAI31 \u_8_15._159_  (
    .A1(\u_8_15._104_ ),
    .A2(\u_8_15._107_ ),
    .A3(\u_8_15._124_ ),
    .B(\u_8_15._106_ ),
    .Y(\u_8_15._126_ )
  );
  MAJ3 \u_8_15._160_  (
    .A1(\u_8_15._102_ ),
    .A2(\u_8_15._103_ ),
    .A3(\u_8_15._126_ ),
    .Y(\u_16_23.nCin )
  );
  OR2 \u_8_15._161_  (
    .A1(\u_0_7._101_ ),
    .A2(\u_8_15._117_ ),
    .Y(\u_8_15._127_ )
  );
  AOI22 \u_8_15._162_  (
    .A1(\u_0_7._101_ ),
    .A2(\u_8_15._116_ ),
    .B1(\u_8_15._118_ ),
    .B2(\u_8_15._127_ ),
    .Y(\u_8_15._092_ )
  );
  XOR2 \u_8_15._163_  (
    .A(A[9]),
    .B(B[9]),
    .Y(\u_8_15._128_ )
  );
  XOR2 \u_8_15._164_  (
    .A(\u_8_15._118_ ),
    .B(\u_8_15._128_ ),
    .Y(\u_8_15._093_ )
  );
  NAND2 \u_8_15._165_  (
    .A1(\u_8_15._113_ ),
    .A2(\u_8_15._115_ ),
    .Y(\u_8_15._129_ )
  );
  XNOR2 \u_8_15._166_  (
    .A(\u_8_15._119_ ),
    .B(\u_8_15._129_ ),
    .Y(\u_8_15._094_ )
  );
  XNOR2 \u_8_15._167_  (
    .A(A[11]),
    .B(B[11]),
    .Y(\u_8_15._130_ )
  );
  XNOR2 \u_8_15._168_  (
    .A(\u_8_15._120_ ),
    .B(\u_8_15._130_ ),
    .Y(\u_8_15._095_ )
  );
  NOR2 \u_8_15._169_  (
    .A1(\u_8_15._109_ ),
    .A2(\u_8_15._111_ ),
    .Y(\u_8_15._131_ )
  );
  XOR2 \u_8_15._170_  (
    .A(\u_8_15._122_ ),
    .B(\u_8_15._131_ ),
    .Y(\u_8_15._096_ )
  );
  NOR2 \u_8_15._171_  (
    .A1(\u_8_15._107_ ),
    .A2(\u_8_15._108_ ),
    .Y(\u_8_15._132_ )
  );
  XOR2 \u_8_15._172_  (
    .A(\u_8_15._123_ ),
    .B(\u_8_15._132_ ),
    .Y(\u_8_15._097_ )
  );
  NOR2 \u_8_15._173_  (
    .A1(\u_8_15._104_ ),
    .A2(\u_8_15._105_ ),
    .Y(\u_8_15._133_ )
  );
  XNOR2 \u_8_15._174_  (
    .A(\u_8_15._125_ ),
    .B(\u_8_15._133_ ),
    .Y(\u_8_15._098_ )
  );
  XNOR2 \u_8_15._175_  (
    .A(A[15]),
    .B(B[15]),
    .Y(\u_8_15._134_ )
  );
  XOR2 \u_8_15._176_  (
    .A(\u_8_15._126_ ),
    .B(\u_8_15._134_ ),
    .Y(\u_8_15._099_ )
  );
  assign \u_24_31.S[3]  = \u_24_31._095_ ;
  assign \u_24_31.S[2]  = \u_24_31._094_ ;
  assign \u_24_31.S[1]  = \u_24_31._093_ ;
  assign \u_24_31.S[0]  = \u_24_31._092_ ;
  assign \u_24_31.B[7]  = B[31];
  assign \u_24_31.B[6]  = B[30];
  assign \u_24_31.B[5]  = B[29];
  assign \u_24_31.B[4]  = B[28];
  assign \u_24_31.B[3]  = B[27];
  assign \u_24_31.B[2]  = B[26];
  assign \u_24_31.B[1]  = B[25];
  assign \u_24_31.B[0]  = B[24];
  assign \u_0_7.A[7]  = A[7];
  assign \u_0_7.A[6]  = A[6];
  assign \u_0_7.A[5]  = A[5];
  assign \u_0_7.A[4]  = A[4];
  assign \u_0_7.A[3]  = A[3];
  assign \u_0_7.A[2]  = A[2];
  assign \u_0_7.A[1]  = A[1];
  assign \u_0_7.A[0]  = A[0];
  assign \u_0_7.S[7]  = \u_0_7._099_ ;
  assign \u_0_7.S[6]  = \u_0_7._098_ ;
  assign \u_0_7.S[5]  = \u_0_7._097_ ;
  assign \u_0_7.S[4]  = \u_0_7._096_ ;
  assign \u_0_7.S[3]  = \u_0_7._095_ ;
  assign \u_0_7.S[2]  = \u_0_7._094_ ;
  assign \u_0_7.S[1]  = \u_0_7._093_ ;
  assign \u_0_7.S[0]  = \u_0_7._092_ ;
  assign \u_0_7.B[7]  = B[7];
  assign \u_0_7.B[6]  = B[6];
  assign \u_0_7.B[5]  = B[5];
  assign \u_0_7.B[4]  = B[4];
  assign \u_0_7.B[3]  = B[3];
  assign \u_0_7.B[2]  = B[2];
  assign \u_0_7.B[1]  = B[1];
  assign \u_0_7.B[0]  = B[0];
  assign \u_16_23.S[7]  = \u_16_23._099_ ;
  assign \u_16_23.S[6]  = \u_16_23._098_ ;
  assign \u_16_23.S[5]  = \u_16_23._097_ ;
  assign \u_16_23.S[4]  = \u_16_23._096_ ;
  assign \u_16_23.S[3]  = \u_16_23._095_ ;
  assign \u_16_23.S[2]  = \u_16_23._094_ ;
  assign \u_16_23.S[1]  = \u_16_23._093_ ;
  assign \u_16_23.S[0]  = \u_16_23._092_ ;
  assign \u_16_23.B[7]  = B[23];
  assign \u_16_23.B[6]  = B[22];
  assign \u_16_23.B[5]  = B[21];
  assign \u_16_23.B[4]  = B[20];
  assign \u_16_23.B[3]  = B[19];
  assign \u_16_23.B[2]  = B[18];
  assign \u_16_23.B[1]  = B[17];
  assign \u_16_23.B[0]  = B[16];
  assign \u_8_15.A[7]  = A[15];
  assign \u_8_15.A[6]  = A[14];
  assign \u_8_15.A[5]  = A[13];
  assign \u_8_15.A[4]  = A[12];
  assign \u_8_15.A[3]  = A[11];
  assign \u_8_15.A[2]  = A[10];
  assign \u_8_15.A[1]  = A[9];
  assign \u_8_15.A[0]  = A[8];
  assign \u_24_31.A[7]  = A[31];
  assign \u_24_31.A[6]  = A[30];
  assign \u_24_31.A[5]  = A[29];
  assign \u_24_31.A[4]  = A[28];
  assign \u_24_31.A[3]  = A[27];
  assign \u_24_31.A[2]  = A[26];
  assign \u_24_31.A[1]  = A[25];
  assign \u_24_31.A[0]  = A[24];
  assign \u_8_15.S[7]  = \u_8_15._099_ ;
  assign \u_8_15.S[6]  = \u_8_15._098_ ;
  assign \u_8_15.S[5]  = \u_8_15._097_ ;
  assign \u_8_15.S[4]  = \u_8_15._096_ ;
  assign \u_8_15.S[3]  = \u_8_15._095_ ;
  assign \u_8_15.S[2]  = \u_8_15._094_ ;
  assign \u_8_15.S[1]  = \u_8_15._093_ ;
  assign \u_8_15.S[0]  = \u_8_15._092_ ;
  assign \u_16_23.A[7]  = A[23];
  assign \u_16_23.A[6]  = A[22];
  assign \u_16_23.A[5]  = A[21];
  assign \u_16_23.A[4]  = A[20];
  assign \u_16_23.A[3]  = A[19];
  assign \u_16_23.A[2]  = A[18];
  assign \u_16_23.A[1]  = A[17];
  assign \u_16_23.A[0]  = A[16];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0]  = B[0];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0]  = A[0];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0]  = B[1];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0]  = A[1];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.B[1]  = B[1];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.B[0]  = B[0];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.A[1]  = A[1];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_low.A[0]  = A[0];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0]  = B[2];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0]  = A[2];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0]  = B[3];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0]  = A[3];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.B[1]  = B[3];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.B[0]  = B[2];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.A[1]  = A[3];
  assign \u_0_7.u_cla.genblk1.u_low.genblk1.u_high.A[0]  = A[2];
  assign \u_0_7.u_cla.genblk1.u_low.B[3]  = B[3];
  assign \u_0_7.u_cla.genblk1.u_low.B[2]  = B[2];
  assign \u_0_7.u_cla.genblk1.u_low.B[1]  = B[1];
  assign \u_0_7.u_cla.genblk1.u_low.B[0]  = B[0];
  assign \u_0_7.u_cla.genblk1.u_low.A[3]  = A[3];
  assign \u_0_7.u_cla.genblk1.u_low.A[2]  = A[2];
  assign \u_0_7.u_cla.genblk1.u_low.A[1]  = A[1];
  assign \u_0_7.u_cla.genblk1.u_low.A[0]  = A[0];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0]  = B[4];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0]  = A[4];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0]  = B[5];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0]  = A[5];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.B[1]  = B[5];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.B[0]  = B[4];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.A[1]  = A[5];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_low.A[0]  = A[4];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0]  = B[6];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0]  = A[6];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0]  = B[7];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0]  = A[7];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.B[1]  = B[7];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.B[0]  = B[6];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.A[1]  = A[7];
  assign \u_0_7.u_cla.genblk1.u_high.genblk1.u_high.A[0]  = A[6];
  assign \u_0_7.u_cla.genblk1.u_high.B[3]  = B[7];
  assign \u_0_7.u_cla.genblk1.u_high.B[2]  = B[6];
  assign \u_0_7.u_cla.genblk1.u_high.B[1]  = B[5];
  assign \u_0_7.u_cla.genblk1.u_high.B[0]  = B[4];
  assign \u_0_7.u_cla.genblk1.u_high.A[3]  = A[7];
  assign \u_0_7.u_cla.genblk1.u_high.A[2]  = A[6];
  assign \u_0_7.u_cla.genblk1.u_high.A[1]  = A[5];
  assign \u_0_7.u_cla.genblk1.u_high.A[0]  = A[4];
  assign \u_0_7.u_cla.B[7]  = B[7];
  assign \u_0_7.u_cla.B[6]  = B[6];
  assign \u_0_7.u_cla.B[5]  = B[5];
  assign \u_0_7.u_cla.B[4]  = B[4];
  assign \u_0_7.u_cla.B[3]  = B[3];
  assign \u_0_7.u_cla.B[2]  = B[2];
  assign \u_0_7.u_cla.B[1]  = B[1];
  assign \u_0_7.u_cla.B[0]  = B[0];
  assign \u_0_7.u_cla.A[7]  = A[7];
  assign \u_0_7.u_cla.A[6]  = A[6];
  assign \u_0_7.u_cla.A[5]  = A[5];
  assign \u_0_7.u_cla.A[4]  = A[4];
  assign \u_0_7.u_cla.A[3]  = A[3];
  assign \u_0_7.u_cla.A[2]  = A[2];
  assign \u_0_7.u_cla.A[1]  = A[1];
  assign \u_0_7.u_cla.A[0]  = A[0];
  assign \u_0_7.nP[-1]  = 1'h1;
  assign \u_0_7.nG[-1]  = 1'h1;
  assign \u_0_7.nCout  = \u_0_7._101_ ;
  assign \u_0_7.nCin  = 1'h1;
  assign \u_0_7.nC[8]  = \u_0_7._101_ ;
  assign \u_0_7.nC[0]  = 1'h1;
  assign \u_8_15.B[3]  = B[11];
  assign \u_8_15.B[2]  = B[10];
  assign \u_8_15.B[4]  = B[12];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0]  = B[16];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0]  = A[16];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0]  = B[17];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0]  = A[17];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.B[1]  = B[17];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.B[0]  = B[16];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.A[1]  = A[17];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_low.A[0]  = A[16];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0]  = B[18];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0]  = A[18];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0]  = B[19];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0]  = A[19];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.B[1]  = B[19];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.B[0]  = B[18];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.A[1]  = A[19];
  assign \u_16_23.u_cla.genblk1.u_low.genblk1.u_high.A[0]  = A[18];
  assign \u_16_23.u_cla.genblk1.u_low.B[3]  = B[19];
  assign \u_16_23.u_cla.genblk1.u_low.B[2]  = B[18];
  assign \u_16_23.u_cla.genblk1.u_low.B[1]  = B[17];
  assign \u_16_23.u_cla.genblk1.u_low.B[0]  = B[16];
  assign \u_16_23.u_cla.genblk1.u_low.A[3]  = A[19];
  assign \u_16_23.u_cla.genblk1.u_low.A[2]  = A[18];
  assign \u_16_23.u_cla.genblk1.u_low.A[1]  = A[17];
  assign \u_16_23.u_cla.genblk1.u_low.A[0]  = A[16];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0]  = B[20];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0]  = A[20];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0]  = B[21];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0]  = A[21];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.B[1]  = B[21];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.B[0]  = B[20];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.A[1]  = A[21];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_low.A[0]  = A[20];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0]  = B[22];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0]  = A[22];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0]  = B[23];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0]  = A[23];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.B[1]  = B[23];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.B[0]  = B[22];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.A[1]  = A[23];
  assign \u_16_23.u_cla.genblk1.u_high.genblk1.u_high.A[0]  = A[22];
  assign \u_16_23.u_cla.genblk1.u_high.B[3]  = B[23];
  assign \u_16_23.u_cla.genblk1.u_high.B[2]  = B[22];
  assign \u_16_23.u_cla.genblk1.u_high.B[1]  = B[21];
  assign \u_16_23.u_cla.genblk1.u_high.B[0]  = B[20];
  assign \u_16_23.u_cla.genblk1.u_high.A[3]  = A[23];
  assign \u_16_23.u_cla.genblk1.u_high.A[2]  = A[22];
  assign \u_16_23.u_cla.genblk1.u_high.A[1]  = A[21];
  assign \u_16_23.u_cla.genblk1.u_high.A[0]  = A[20];
  assign \u_16_23.u_cla.B[7]  = B[23];
  assign \u_16_23.u_cla.B[6]  = B[22];
  assign \u_16_23.u_cla.B[5]  = B[21];
  assign \u_16_23.u_cla.B[4]  = B[20];
  assign \u_16_23.u_cla.B[3]  = B[19];
  assign \u_16_23.u_cla.B[2]  = B[18];
  assign \u_16_23.u_cla.B[1]  = B[17];
  assign \u_16_23.u_cla.B[0]  = B[16];
  assign \u_16_23.u_cla.A[7]  = A[23];
  assign \u_16_23.u_cla.A[6]  = A[22];
  assign \u_16_23.u_cla.A[5]  = A[21];
  assign \u_16_23.u_cla.A[4]  = A[20];
  assign \u_16_23.u_cla.A[3]  = A[19];
  assign \u_16_23.u_cla.A[2]  = A[18];
  assign \u_16_23.u_cla.A[1]  = A[17];
  assign \u_16_23.u_cla.A[0]  = A[16];
  assign \u_16_23.nP[-1]  = 1'h1;
  assign \u_16_23.nG[-1]  = \u_16_23.nCin ;
  assign \u_16_23.nCout  = \u_16_23._101_ ;
  assign \u_16_23.nC[8]  = \u_16_23._101_ ;
  assign \u_16_23.nC[0]  = \u_16_23.nCin ;
  assign \u_8_15.B[1]  = B[9];
  assign \u_8_15.B[0]  = B[8];
  assign \u_24_31.S[4]  = \u_24_31._096_ ;
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0]  = B[24];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0]  = A[24];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0]  = B[25];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0]  = A[25];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.B[1]  = B[25];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.B[0]  = B[24];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.A[1]  = A[25];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_low.A[0]  = A[24];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0]  = B[26];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0]  = A[26];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0]  = B[27];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0]  = A[27];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.B[1]  = B[27];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.B[0]  = B[26];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.A[1]  = A[27];
  assign \u_24_31.u_cla.genblk1.u_low.genblk1.u_high.A[0]  = A[26];
  assign \u_24_31.u_cla.genblk1.u_low.B[3]  = B[27];
  assign \u_24_31.u_cla.genblk1.u_low.B[2]  = B[26];
  assign \u_24_31.u_cla.genblk1.u_low.B[1]  = B[25];
  assign \u_24_31.u_cla.genblk1.u_low.B[0]  = B[24];
  assign \u_24_31.u_cla.genblk1.u_low.A[3]  = A[27];
  assign \u_24_31.u_cla.genblk1.u_low.A[2]  = A[26];
  assign \u_24_31.u_cla.genblk1.u_low.A[1]  = A[25];
  assign \u_24_31.u_cla.genblk1.u_low.A[0]  = A[24];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0]  = B[28];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0]  = A[28];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0]  = B[29];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0]  = A[29];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.B[1]  = B[29];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.B[0]  = B[28];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.A[1]  = A[29];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_low.A[0]  = A[28];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0]  = B[30];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0]  = A[30];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0]  = B[31];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0]  = A[31];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.B[1]  = B[31];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.B[0]  = B[30];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.A[1]  = A[31];
  assign \u_24_31.u_cla.genblk1.u_high.genblk1.u_high.A[0]  = A[30];
  assign \u_24_31.u_cla.genblk1.u_high.B[3]  = B[31];
  assign \u_24_31.u_cla.genblk1.u_high.B[2]  = B[30];
  assign \u_24_31.u_cla.genblk1.u_high.B[1]  = B[29];
  assign \u_24_31.u_cla.genblk1.u_high.B[0]  = B[28];
  assign \u_24_31.u_cla.genblk1.u_high.A[3]  = A[31];
  assign \u_24_31.u_cla.genblk1.u_high.A[2]  = A[30];
  assign \u_24_31.u_cla.genblk1.u_high.A[1]  = A[29];
  assign \u_24_31.u_cla.genblk1.u_high.A[0]  = A[28];
  assign \u_24_31.u_cla.B[7]  = B[31];
  assign \u_24_31.u_cla.B[6]  = B[30];
  assign \u_24_31.u_cla.B[5]  = B[29];
  assign \u_24_31.u_cla.B[4]  = B[28];
  assign \u_24_31.u_cla.B[3]  = B[27];
  assign \u_24_31.u_cla.B[2]  = B[26];
  assign \u_24_31.u_cla.B[1]  = B[25];
  assign \u_24_31.u_cla.B[0]  = B[24];
  assign \u_24_31.u_cla.A[7]  = A[31];
  assign \u_24_31.u_cla.A[6]  = A[30];
  assign \u_24_31.u_cla.A[5]  = A[29];
  assign \u_24_31.u_cla.A[4]  = A[28];
  assign \u_24_31.u_cla.A[3]  = A[27];
  assign \u_24_31.u_cla.A[2]  = A[26];
  assign \u_24_31.u_cla.A[1]  = A[25];
  assign \u_24_31.u_cla.A[0]  = A[24];
  assign \u_24_31.nP[-1]  = 1'h1;
  assign \u_24_31.nG[-1]  = \u_16_23._101_ ;
  assign \u_24_31.nCout  = \u_24_31._101_ ;
  assign \u_24_31.nCin  = \u_16_23._101_ ;
  assign \u_24_31.nC[8]  = \u_24_31._101_ ;
  assign \u_24_31.nC[0]  = \u_16_23._101_ ;
  assign \u_8_15.B[6]  = B[14];
  assign \u_8_15.B[5]  = B[13];
  assign \u_24_31.S[6]  = \u_24_31._098_ ;
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0]  = B[8];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0]  = A[8];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0]  = B[9];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0]  = A[9];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.B[1]  = B[9];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.B[0]  = B[8];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.A[1]  = A[9];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_low.A[0]  = A[8];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0]  = B[10];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0]  = A[10];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0]  = B[11];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0]  = A[11];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.B[1]  = B[11];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.B[0]  = B[10];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.A[1]  = A[11];
  assign \u_8_15.u_cla.genblk1.u_low.genblk1.u_high.A[0]  = A[10];
  assign \u_8_15.u_cla.genblk1.u_low.B[3]  = B[11];
  assign \u_8_15.u_cla.genblk1.u_low.B[2]  = B[10];
  assign \u_8_15.u_cla.genblk1.u_low.B[1]  = B[9];
  assign \u_8_15.u_cla.genblk1.u_low.B[0]  = B[8];
  assign \u_8_15.u_cla.genblk1.u_low.A[3]  = A[11];
  assign \u_8_15.u_cla.genblk1.u_low.A[2]  = A[10];
  assign \u_8_15.u_cla.genblk1.u_low.A[1]  = A[9];
  assign \u_8_15.u_cla.genblk1.u_low.A[0]  = A[8];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0]  = B[12];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0]  = A[12];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0]  = B[13];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0]  = A[13];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.B[1]  = B[13];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.B[0]  = B[12];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.A[1]  = A[13];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_low.A[0]  = A[12];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0]  = B[14];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0]  = A[14];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0]  = B[15];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0]  = A[15];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.B[1]  = B[15];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.B[0]  = B[14];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.A[1]  = A[15];
  assign \u_8_15.u_cla.genblk1.u_high.genblk1.u_high.A[0]  = A[14];
  assign \u_8_15.u_cla.genblk1.u_high.B[3]  = B[15];
  assign \u_8_15.u_cla.genblk1.u_high.B[2]  = B[14];
  assign \u_8_15.u_cla.genblk1.u_high.B[1]  = B[13];
  assign \u_8_15.u_cla.genblk1.u_high.B[0]  = B[12];
  assign \u_8_15.u_cla.genblk1.u_high.A[3]  = A[15];
  assign \u_8_15.u_cla.genblk1.u_high.A[2]  = A[14];
  assign \u_8_15.u_cla.genblk1.u_high.A[1]  = A[13];
  assign \u_8_15.u_cla.genblk1.u_high.A[0]  = A[12];
  assign \u_8_15.u_cla.B[7]  = B[15];
  assign \u_8_15.u_cla.B[6]  = B[14];
  assign \u_8_15.u_cla.B[5]  = B[13];
  assign \u_8_15.u_cla.B[4]  = B[12];
  assign \u_8_15.u_cla.B[3]  = B[11];
  assign \u_8_15.u_cla.B[2]  = B[10];
  assign \u_8_15.u_cla.B[1]  = B[9];
  assign \u_8_15.u_cla.B[0]  = B[8];
  assign \u_8_15.u_cla.A[7]  = A[15];
  assign \u_8_15.u_cla.A[6]  = A[14];
  assign \u_8_15.u_cla.A[5]  = A[13];
  assign \u_8_15.u_cla.A[4]  = A[12];
  assign \u_8_15.u_cla.A[3]  = A[11];
  assign \u_8_15.u_cla.A[2]  = A[10];
  assign \u_8_15.u_cla.A[1]  = A[9];
  assign \u_8_15.u_cla.A[0]  = A[8];
  assign \u_8_15.nP[-1]  = 1'h1;
  assign \u_8_15.nG[-1]  = \u_0_7._101_ ;
  assign \u_8_15.nCout  = \u_16_23.nCin ;
  assign \u_8_15.nCin  = \u_0_7._101_ ;
  assign \u_8_15.nC[8]  = \u_16_23.nCin ;
  assign \u_8_15.nC[0]  = \u_0_7._101_ ;
  assign \u_8_15._101_  = \u_16_23.nCin ;
  assign \u_24_31.S[5]  = \u_24_31._097_ ;
  assign \u_8_15.B[7]  = B[15];
  assign \u_24_31.S[7]  = \u_24_31._099_ ;
  assign S = { \u_24_31._099_ , \u_24_31._098_ , \u_24_31._097_ , \u_24_31._096_ , \u_24_31._095_ , \u_24_31._094_ , \u_24_31._093_ , \u_24_31._092_ , \u_16_23._099_ , \u_16_23._098_ , \u_16_23._097_ , \u_16_23._096_ , \u_16_23._095_ , \u_16_23._094_ , \u_16_23._093_ , \u_16_23._092_ , \u_8_15._099_ , \u_8_15._098_ , \u_8_15._097_ , \u_8_15._096_ , \u_8_15._095_ , \u_8_15._094_ , \u_8_15._093_ , \u_8_15._092_ , \u_0_7._099_ , \u_0_7._098_ , \u_0_7._097_ , \u_0_7._096_ , \u_0_7._095_ , \u_0_7._094_ , \u_0_7._093_ , \u_0_7._092_  };
  assign nCout = \u_24_31._101_ ;
  assign nG0_7 = \u_0_7._101_ ;
  assign nG16_23 = \u_16_23._101_ ;
  assign nG8_15 = \u_16_23.nCin ;
endmodule
