/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, clang++ 18.1.8 -fPIC -O3) */

module alu8(A, B, nCin, S, nCout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  output [7:0] S;
  wire [7:0] S;
  wire \nC[0] ;
  wire \nC[8] ;
  input nCin;
  wire nCin;
  output nCout;
  wire nCout;
  wire \nG[-1] ;
  wire \nP[-1] ;
  wire \u_cla.A[0] ;
  wire \u_cla.A[1] ;
  wire \u_cla.A[2] ;
  wire \u_cla.A[3] ;
  wire \u_cla.A[4] ;
  wire \u_cla.A[5] ;
  wire \u_cla.A[6] ;
  wire \u_cla.A[7] ;
  wire \u_cla.B[0] ;
  wire \u_cla.B[1] ;
  wire \u_cla.B[2] ;
  wire \u_cla.B[3] ;
  wire \u_cla.B[4] ;
  wire \u_cla.B[5] ;
  wire \u_cla.B[6] ;
  wire \u_cla.B[7] ;
  wire \u_cla.genblk1.u_high.A[0] ;
  wire \u_cla.genblk1.u_high.A[1] ;
  wire \u_cla.genblk1.u_high.A[2] ;
  wire \u_cla.genblk1.u_high.A[3] ;
  wire \u_cla.genblk1.u_high.B[0] ;
  wire \u_cla.genblk1.u_high.B[1] ;
  wire \u_cla.genblk1.u_high.B[2] ;
  wire \u_cla.genblk1.u_high.B[3] ;
  wire \u_cla.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_high.A[1] ;
  wire \u_cla.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_high.B[1] ;
  wire \u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_low.A[1] ;
  wire \u_cla.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_low.B[1] ;
  wire \u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_cla.genblk1.u_low.A[0] ;
  wire \u_cla.genblk1.u_low.A[1] ;
  wire \u_cla.genblk1.u_low.A[2] ;
  wire \u_cla.genblk1.u_low.A[3] ;
  wire \u_cla.genblk1.u_low.B[0] ;
  wire \u_cla.genblk1.u_low.B[1] ;
  wire \u_cla.genblk1.u_low.B[2] ;
  wire \u_cla.genblk1.u_low.B[3] ;
  wire \u_cla.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_high.A[1] ;
  wire \u_cla.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_high.B[1] ;
  wire \u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_low.A[1] ;
  wire \u_cla.genblk1.u_low.genblk1.u_low.B[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_low.B[1] ;
  wire \u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0] ;
  wire \u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0] ;
  NOT _135_ (
    .A(_083_),
    .Y(_102_)
  );
  NOT _136_ (
    .A(_091_),
    .Y(_103_)
  );
  AND2 _137_ (
    .A1(_082_),
    .A2(_090_),
    .Y(_104_)
  );
  NOR2 _138_ (
    .A1(_082_),
    .A2(_090_),
    .Y(_105_)
  );
  OR2 _139_ (
    .A1(_082_),
    .A2(_090_),
    .Y(_106_)
  );
  AND2 _140_ (
    .A1(_081_),
    .A2(_089_),
    .Y(_107_)
  );
  NOR2 _141_ (
    .A1(_081_),
    .A2(_089_),
    .Y(_108_)
  );
  AND2 _142_ (
    .A1(_080_),
    .A2(_088_),
    .Y(_109_)
  );
  NOT _143_ (
    .A(_109_),
    .Y(_110_)
  );
  NOR2 _144_ (
    .A1(_080_),
    .A2(_088_),
    .Y(_111_)
  );
  NAND2 _145_ (
    .A1(_079_),
    .A2(_087_),
    .Y(_112_)
  );
  NAND2 _146_ (
    .A1(_078_),
    .A2(_086_),
    .Y(_113_)
  );
  NOT _147_ (
    .A(_113_),
    .Y(_114_)
  );
  OR2 _148_ (
    .A1(_078_),
    .A2(_086_),
    .Y(_115_)
  );
  NOR2 _149_ (
    .A1(_076_),
    .A2(_084_),
    .Y(_116_)
  );
  NAND2 _150_ (
    .A1(_076_),
    .A2(_084_),
    .Y(_117_)
  );
  OAI21 _151_ (
    .A(_117_),
    .B1(_116_),
    .B2(_100_),
    .Y(_118_)
  );
  MAJ3 _152_ (
    .A1(_077_),
    .A2(_085_),
    .A3(_118_),
    .Y(_119_)
  );
  OA21 _153_ (
    .A(_115_),
    .B1(_119_),
    .B2(_114_),
    .Y(_120_)
  );
  OAI221 _154_ (
    .A1(_079_),
    .A2(_087_),
    .B1(_114_),
    .B2(_119_),
    .C(_115_),
    .Y(_121_)
  );
  NAND2 _155_ (
    .A1(_112_),
    .A2(_121_),
    .Y(_122_)
  );
  MAJ3 _156_ (
    .A1(_080_),
    .A2(_088_),
    .A3(_122_),
    .Y(_123_)
  );
  AOI311 _157_ (
    .A1(_110_),
    .A2(_112_),
    .A3(_121_),
    .B1(_111_),
    .C1(_108_),
    .Y(_124_)
  );
  NOR2 _158_ (
    .A1(_107_),
    .A2(_124_),
    .Y(_125_)
  );
  OAI31 _159_ (
    .A1(_104_),
    .A2(_107_),
    .A3(_124_),
    .B(_106_),
    .Y(_126_)
  );
  MAJ3 _160_ (
    .A1(_102_),
    .A2(_103_),
    .A3(_126_),
    .Y(_101_)
  );
  OR2 _161_ (
    .A1(_100_),
    .A2(_117_),
    .Y(_127_)
  );
  AOI22 _162_ (
    .A1(_100_),
    .A2(_116_),
    .B1(_118_),
    .B2(_127_),
    .Y(_092_)
  );
  XOR2 _163_ (
    .A(_077_),
    .B(_085_),
    .Y(_128_)
  );
  XOR2 _164_ (
    .A(_118_),
    .B(_128_),
    .Y(_093_)
  );
  NAND2 _165_ (
    .A1(_113_),
    .A2(_115_),
    .Y(_129_)
  );
  XNOR2 _166_ (
    .A(_119_),
    .B(_129_),
    .Y(_094_)
  );
  XNOR2 _167_ (
    .A(_079_),
    .B(_087_),
    .Y(_130_)
  );
  XNOR2 _168_ (
    .A(_120_),
    .B(_130_),
    .Y(_095_)
  );
  NOR2 _169_ (
    .A1(_109_),
    .A2(_111_),
    .Y(_131_)
  );
  XOR2 _170_ (
    .A(_122_),
    .B(_131_),
    .Y(_096_)
  );
  NOR2 _171_ (
    .A1(_107_),
    .A2(_108_),
    .Y(_132_)
  );
  XOR2 _172_ (
    .A(_123_),
    .B(_132_),
    .Y(_097_)
  );
  NOR2 _173_ (
    .A1(_104_),
    .A2(_105_),
    .Y(_133_)
  );
  XNOR2 _174_ (
    .A(_125_),
    .B(_133_),
    .Y(_098_)
  );
  XNOR2 _175_ (
    .A(_083_),
    .B(_091_),
    .Y(_134_)
  );
  XOR2 _176_ (
    .A(_126_),
    .B(_134_),
    .Y(_099_)
  );
  assign \u_cla.A[3]  = A[3];
  assign \u_cla.A[4]  = A[4];
  assign \u_cla.A[5]  = A[5];
  assign \u_cla.A[6]  = A[6];
  assign \u_cla.A[7]  = A[7];
  assign \u_cla.B[0]  = B[0];
  assign \u_cla.B[1]  = B[1];
  assign \u_cla.B[2]  = B[2];
  assign \u_cla.B[3]  = B[3];
  assign \u_cla.B[4]  = B[4];
  assign \u_cla.B[5]  = B[5];
  assign \u_cla.B[6]  = B[6];
  assign \u_cla.B[7]  = B[7];
  assign \u_cla.genblk1.u_high.A[0]  = A[4];
  assign \u_cla.genblk1.u_high.A[1]  = A[5];
  assign \u_cla.genblk1.u_high.A[2]  = A[6];
  assign \u_cla.genblk1.u_high.A[3]  = A[7];
  assign \u_cla.genblk1.u_high.B[0]  = B[4];
  assign \u_cla.genblk1.u_high.B[1]  = B[5];
  assign \u_cla.genblk1.u_high.B[2]  = B[6];
  assign \u_cla.genblk1.u_high.B[3]  = B[7];
  assign \u_cla.genblk1.u_high.genblk1.u_high.A[0]  = A[6];
  assign \u_cla.genblk1.u_high.genblk1.u_high.A[1]  = A[7];
  assign \u_cla.genblk1.u_high.genblk1.u_high.B[0]  = B[6];
  assign \u_cla.genblk1.u_high.genblk1.u_high.B[1]  = B[7];
  assign \u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.A[0]  = A[7];
  assign \u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_high.B[0]  = B[7];
  assign \u_cla.A[2]  = A[2];
  assign \u_cla.A[1]  = A[1];
  assign \u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.A[0]  = A[6];
  assign \u_cla.genblk1.u_high.genblk1.u_high.genblk1.u_low.B[0]  = B[6];
  assign \u_cla.A[0]  = A[0];
  assign \u_cla.genblk1.u_high.genblk1.u_low.A[0]  = A[4];
  assign \u_cla.genblk1.u_high.genblk1.u_low.A[1]  = A[5];
  assign \u_cla.genblk1.u_high.genblk1.u_low.B[0]  = B[4];
  assign \u_cla.genblk1.u_high.genblk1.u_low.B[1]  = B[5];
  assign \u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.A[0]  = A[5];
  assign \u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_high.B[0]  = B[5];
  assign \u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.A[0]  = A[4];
  assign \u_cla.genblk1.u_high.genblk1.u_low.genblk1.u_low.B[0]  = B[4];
  assign \nP[-1]  = 1'h1;
  assign \nG[-1]  = nCin;
  assign \nC[8]  = nCout;
  assign \u_cla.genblk1.u_low.A[0]  = A[0];
  assign \u_cla.genblk1.u_low.A[1]  = A[1];
  assign \u_cla.genblk1.u_low.A[2]  = A[2];
  assign \u_cla.genblk1.u_low.A[3]  = A[3];
  assign \u_cla.genblk1.u_low.B[0]  = B[0];
  assign \u_cla.genblk1.u_low.B[1]  = B[1];
  assign \u_cla.genblk1.u_low.B[2]  = B[2];
  assign \u_cla.genblk1.u_low.B[3]  = B[3];
  assign \u_cla.genblk1.u_low.genblk1.u_high.A[0]  = A[2];
  assign \u_cla.genblk1.u_low.genblk1.u_high.A[1]  = A[3];
  assign \u_cla.genblk1.u_low.genblk1.u_high.B[0]  = B[2];
  assign \u_cla.genblk1.u_low.genblk1.u_high.B[1]  = B[3];
  assign \u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.A[0]  = A[3];
  assign \u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_high.B[0]  = B[3];
  assign \nC[0]  = nCin;
  assign \u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.A[0]  = A[2];
  assign \u_cla.genblk1.u_low.genblk1.u_high.genblk1.u_low.B[0]  = B[2];
  assign \u_cla.genblk1.u_low.genblk1.u_low.A[0]  = A[0];
  assign \u_cla.genblk1.u_low.genblk1.u_low.A[1]  = A[1];
  assign \u_cla.genblk1.u_low.genblk1.u_low.B[0]  = B[0];
  assign \u_cla.genblk1.u_low.genblk1.u_low.B[1]  = B[1];
  assign \u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.A[0]  = A[1];
  assign \u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_high.B[0]  = B[1];
  assign \u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.A[0]  = A[0];
  assign \u_cla.genblk1.u_low.genblk1.u_low.genblk1.u_low.B[0]  = B[0];
  assign _083_ = A[7];
  assign _091_ = B[7];
  assign _082_ = A[6];
  assign _090_ = B[6];
  assign _081_ = A[5];
  assign _089_ = B[5];
  assign _080_ = A[4];
  assign _088_ = B[4];
  assign _079_ = A[3];
  assign _087_ = B[3];
  assign _078_ = A[2];
  assign _086_ = B[2];
  assign _077_ = A[1];
  assign _085_ = B[1];
  assign _076_ = A[0];
  assign _084_ = B[0];
  assign _100_ = nCin;
  assign nCout = _101_;
  assign S[0] = _092_;
  assign S[1] = _093_;
  assign S[2] = _094_;
  assign S[3] = _095_;
  assign S[4] = _096_;
  assign S[5] = _097_;
  assign S[6] = _098_;
  assign S[7] = _099_;
endmodule
