/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, clang++ 18.1.8 -fPIC -O3) */

module adder(A, B, nCin, S, nCout);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  output [7:0] S;
  wire [7:0] S;
  wire \genblk1[0].FA.A ;
  wire \genblk1[0].FA.AxB ;
  wire \genblk1[0].FA.B ;
  wire \genblk1[0].FA.Cin ;
  wire \genblk1[0].FA.S ;
  wire \genblk1[0].FA.nA ;
  wire \genblk1[0].FA.nAxB ;
  wire \genblk1[0].FA.nB ;
  wire \genblk1[0].FA.nCin ;
  wire \genblk1[0].FA.nCout ;
  wire \genblk1[1].FA.A ;
  wire \genblk1[1].FA.AxB ;
  wire \genblk1[1].FA.B ;
  wire \genblk1[1].FA.Cin ;
  wire \genblk1[1].FA.S ;
  wire \genblk1[1].FA.nA ;
  wire \genblk1[1].FA.nAxB ;
  wire \genblk1[1].FA.nB ;
  wire \genblk1[1].FA.nCin ;
  wire \genblk1[1].FA.nCout ;
  wire \genblk1[2].FA.A ;
  wire \genblk1[2].FA.AxB ;
  wire \genblk1[2].FA.B ;
  wire \genblk1[2].FA.Cin ;
  wire \genblk1[2].FA.S ;
  wire \genblk1[2].FA.nA ;
  wire \genblk1[2].FA.nAxB ;
  wire \genblk1[2].FA.nB ;
  wire \genblk1[2].FA.nCin ;
  wire \genblk1[2].FA.nCout ;
  wire \genblk1[3].FA.A ;
  wire \genblk1[3].FA.AxB ;
  wire \genblk1[3].FA.B ;
  wire \genblk1[3].FA.Cin ;
  wire \genblk1[3].FA.S ;
  wire \genblk1[3].FA.nA ;
  wire \genblk1[3].FA.nAxB ;
  wire \genblk1[3].FA.nB ;
  wire \genblk1[3].FA.nCin ;
  wire \genblk1[3].FA.nCout ;
  wire \genblk1[4].FA.A ;
  wire \genblk1[4].FA.AxB ;
  wire \genblk1[4].FA.B ;
  wire \genblk1[4].FA.Cin ;
  wire \genblk1[4].FA.S ;
  wire \genblk1[4].FA.nA ;
  wire \genblk1[4].FA.nAxB ;
  wire \genblk1[4].FA.nB ;
  wire \genblk1[4].FA.nCin ;
  wire \genblk1[4].FA.nCout ;
  wire \genblk1[5].FA.A ;
  wire \genblk1[5].FA.AxB ;
  wire \genblk1[5].FA.B ;
  wire \genblk1[5].FA.Cin ;
  wire \genblk1[5].FA.S ;
  wire \genblk1[5].FA.nA ;
  wire \genblk1[5].FA.nAxB ;
  wire \genblk1[5].FA.nB ;
  wire \genblk1[5].FA.nCin ;
  wire \genblk1[5].FA.nCout ;
  wire \genblk1[6].FA.A ;
  wire \genblk1[6].FA.AxB ;
  wire \genblk1[6].FA.B ;
  wire \genblk1[6].FA.Cin ;
  wire \genblk1[6].FA.S ;
  wire \genblk1[6].FA.nA ;
  wire \genblk1[6].FA.nAxB ;
  wire \genblk1[6].FA.nB ;
  wire \genblk1[6].FA.nCin ;
  wire \genblk1[6].FA.nCout ;
  wire \genblk1[7].FA.A ;
  wire \genblk1[7].FA.AxB ;
  wire \genblk1[7].FA.B ;
  wire \genblk1[7].FA.Cin ;
  wire \genblk1[7].FA.S ;
  wire \genblk1[7].FA.nA ;
  wire \genblk1[7].FA.nAxB ;
  wire \genblk1[7].FA.nB ;
  wire \genblk1[7].FA.nCin ;
  wire \genblk1[7].FA.nCout ;
  wire \nC[-1] ;
  wire \nC[0] ;
  wire \nC[1] ;
  wire \nC[2] ;
  wire \nC[3] ;
  wire \nC[4] ;
  wire \nC[5] ;
  wire \nC[6] ;
  wire \nC[7] ;
  input nCin;
  wire nCin;
  output nCout;
  wire nCout;
  AOI22 \genblk1[0].FA.XAxB  (
    .A1(A[0]),
    .A2(B[0]),
    .B1(\genblk1[0].FA.nA ),
    .B2(\genblk1[0].FA.nB ),
    .Y(\genblk1[0].FA.AxB )
  );
  NOT \genblk1[0].FA.XCin  (
    .A(nCin),
    .Y(\genblk1[0].FA.Cin )
  );
  AOI22 \genblk1[0].FA.XS  (
    .A1(\genblk1[0].FA.nAxB ),
    .A2(nCin),
    .B1(\genblk1[0].FA.AxB ),
    .B2(\genblk1[0].FA.Cin ),
    .Y(\genblk1[0].FA.S )
  );
  NOT \genblk1[0].FA.XnA  (
    .A(A[0]),
    .Y(\genblk1[0].FA.nA )
  );
  NOT \genblk1[0].FA.XnAxB  (
    .A(\genblk1[0].FA.AxB ),
    .Y(\genblk1[0].FA.nAxB )
  );
  NOT \genblk1[0].FA.XnB  (
    .A(B[0]),
    .Y(\genblk1[0].FA.nB )
  );
  AOI22 \genblk1[0].FA.XnCout  (
    .A1(A[0]),
    .A2(B[0]),
    .B1(\genblk1[0].FA.Cin ),
    .B2(\genblk1[0].FA.AxB ),
    .Y(\genblk1[0].FA.nCout )
  );
  AOI22 \genblk1[1].FA.XAxB  (
    .A1(A[1]),
    .A2(B[1]),
    .B1(\genblk1[1].FA.nA ),
    .B2(\genblk1[1].FA.nB ),
    .Y(\genblk1[1].FA.AxB )
  );
  NOT \genblk1[1].FA.XCin  (
    .A(\genblk1[0].FA.nCout ),
    .Y(\genblk1[1].FA.Cin )
  );
  AOI22 \genblk1[1].FA.XS  (
    .A1(\genblk1[1].FA.nAxB ),
    .A2(\genblk1[0].FA.nCout ),
    .B1(\genblk1[1].FA.AxB ),
    .B2(\genblk1[1].FA.Cin ),
    .Y(\genblk1[1].FA.S )
  );
  NOT \genblk1[1].FA.XnA  (
    .A(A[1]),
    .Y(\genblk1[1].FA.nA )
  );
  NOT \genblk1[1].FA.XnAxB  (
    .A(\genblk1[1].FA.AxB ),
    .Y(\genblk1[1].FA.nAxB )
  );
  NOT \genblk1[1].FA.XnB  (
    .A(B[1]),
    .Y(\genblk1[1].FA.nB )
  );
  AOI22 \genblk1[1].FA.XnCout  (
    .A1(A[1]),
    .A2(B[1]),
    .B1(\genblk1[1].FA.Cin ),
    .B2(\genblk1[1].FA.AxB ),
    .Y(\genblk1[1].FA.nCout )
  );
  AOI22 \genblk1[2].FA.XAxB  (
    .A1(A[2]),
    .A2(B[2]),
    .B1(\genblk1[2].FA.nA ),
    .B2(\genblk1[2].FA.nB ),
    .Y(\genblk1[2].FA.AxB )
  );
  NOT \genblk1[2].FA.XCin  (
    .A(\genblk1[1].FA.nCout ),
    .Y(\genblk1[2].FA.Cin )
  );
  AOI22 \genblk1[2].FA.XS  (
    .A1(\genblk1[2].FA.nAxB ),
    .A2(\genblk1[1].FA.nCout ),
    .B1(\genblk1[2].FA.AxB ),
    .B2(\genblk1[2].FA.Cin ),
    .Y(\genblk1[2].FA.S )
  );
  NOT \genblk1[2].FA.XnA  (
    .A(A[2]),
    .Y(\genblk1[2].FA.nA )
  );
  NOT \genblk1[2].FA.XnAxB  (
    .A(\genblk1[2].FA.AxB ),
    .Y(\genblk1[2].FA.nAxB )
  );
  NOT \genblk1[2].FA.XnB  (
    .A(B[2]),
    .Y(\genblk1[2].FA.nB )
  );
  AOI22 \genblk1[2].FA.XnCout  (
    .A1(A[2]),
    .A2(B[2]),
    .B1(\genblk1[2].FA.Cin ),
    .B2(\genblk1[2].FA.AxB ),
    .Y(\genblk1[2].FA.nCout )
  );
  AOI22 \genblk1[3].FA.XAxB  (
    .A1(A[3]),
    .A2(B[3]),
    .B1(\genblk1[3].FA.nA ),
    .B2(\genblk1[3].FA.nB ),
    .Y(\genblk1[3].FA.AxB )
  );
  NOT \genblk1[3].FA.XCin  (
    .A(\genblk1[2].FA.nCout ),
    .Y(\genblk1[3].FA.Cin )
  );
  AOI22 \genblk1[3].FA.XS  (
    .A1(\genblk1[3].FA.nAxB ),
    .A2(\genblk1[2].FA.nCout ),
    .B1(\genblk1[3].FA.AxB ),
    .B2(\genblk1[3].FA.Cin ),
    .Y(\genblk1[3].FA.S )
  );
  NOT \genblk1[3].FA.XnA  (
    .A(A[3]),
    .Y(\genblk1[3].FA.nA )
  );
  NOT \genblk1[3].FA.XnAxB  (
    .A(\genblk1[3].FA.AxB ),
    .Y(\genblk1[3].FA.nAxB )
  );
  NOT \genblk1[3].FA.XnB  (
    .A(B[3]),
    .Y(\genblk1[3].FA.nB )
  );
  AOI22 \genblk1[3].FA.XnCout  (
    .A1(A[3]),
    .A2(B[3]),
    .B1(\genblk1[3].FA.Cin ),
    .B2(\genblk1[3].FA.AxB ),
    .Y(\genblk1[3].FA.nCout )
  );
  AOI22 \genblk1[4].FA.XAxB  (
    .A1(A[4]),
    .A2(B[4]),
    .B1(\genblk1[4].FA.nA ),
    .B2(\genblk1[4].FA.nB ),
    .Y(\genblk1[4].FA.AxB )
  );
  NOT \genblk1[4].FA.XCin  (
    .A(\genblk1[3].FA.nCout ),
    .Y(\genblk1[4].FA.Cin )
  );
  AOI22 \genblk1[4].FA.XS  (
    .A1(\genblk1[4].FA.nAxB ),
    .A2(\genblk1[3].FA.nCout ),
    .B1(\genblk1[4].FA.AxB ),
    .B2(\genblk1[4].FA.Cin ),
    .Y(\genblk1[4].FA.S )
  );
  NOT \genblk1[4].FA.XnA  (
    .A(A[4]),
    .Y(\genblk1[4].FA.nA )
  );
  NOT \genblk1[4].FA.XnAxB  (
    .A(\genblk1[4].FA.AxB ),
    .Y(\genblk1[4].FA.nAxB )
  );
  NOT \genblk1[4].FA.XnB  (
    .A(B[4]),
    .Y(\genblk1[4].FA.nB )
  );
  AOI22 \genblk1[4].FA.XnCout  (
    .A1(A[4]),
    .A2(B[4]),
    .B1(\genblk1[4].FA.Cin ),
    .B2(\genblk1[4].FA.AxB ),
    .Y(\genblk1[4].FA.nCout )
  );
  AOI22 \genblk1[5].FA.XAxB  (
    .A1(A[5]),
    .A2(B[5]),
    .B1(\genblk1[5].FA.nA ),
    .B2(\genblk1[5].FA.nB ),
    .Y(\genblk1[5].FA.AxB )
  );
  NOT \genblk1[5].FA.XCin  (
    .A(\genblk1[4].FA.nCout ),
    .Y(\genblk1[5].FA.Cin )
  );
  AOI22 \genblk1[5].FA.XS  (
    .A1(\genblk1[5].FA.nAxB ),
    .A2(\genblk1[4].FA.nCout ),
    .B1(\genblk1[5].FA.AxB ),
    .B2(\genblk1[5].FA.Cin ),
    .Y(\genblk1[5].FA.S )
  );
  NOT \genblk1[5].FA.XnA  (
    .A(A[5]),
    .Y(\genblk1[5].FA.nA )
  );
  NOT \genblk1[5].FA.XnAxB  (
    .A(\genblk1[5].FA.AxB ),
    .Y(\genblk1[5].FA.nAxB )
  );
  NOT \genblk1[5].FA.XnB  (
    .A(B[5]),
    .Y(\genblk1[5].FA.nB )
  );
  AOI22 \genblk1[5].FA.XnCout  (
    .A1(A[5]),
    .A2(B[5]),
    .B1(\genblk1[5].FA.Cin ),
    .B2(\genblk1[5].FA.AxB ),
    .Y(\genblk1[5].FA.nCout )
  );
  AOI22 \genblk1[6].FA.XAxB  (
    .A1(A[6]),
    .A2(B[6]),
    .B1(\genblk1[6].FA.nA ),
    .B2(\genblk1[6].FA.nB ),
    .Y(\genblk1[6].FA.AxB )
  );
  NOT \genblk1[6].FA.XCin  (
    .A(\genblk1[5].FA.nCout ),
    .Y(\genblk1[6].FA.Cin )
  );
  AOI22 \genblk1[6].FA.XS  (
    .A1(\genblk1[6].FA.nAxB ),
    .A2(\genblk1[5].FA.nCout ),
    .B1(\genblk1[6].FA.AxB ),
    .B2(\genblk1[6].FA.Cin ),
    .Y(\genblk1[6].FA.S )
  );
  NOT \genblk1[6].FA.XnA  (
    .A(A[6]),
    .Y(\genblk1[6].FA.nA )
  );
  NOT \genblk1[6].FA.XnAxB  (
    .A(\genblk1[6].FA.AxB ),
    .Y(\genblk1[6].FA.nAxB )
  );
  NOT \genblk1[6].FA.XnB  (
    .A(B[6]),
    .Y(\genblk1[6].FA.nB )
  );
  AOI22 \genblk1[6].FA.XnCout  (
    .A1(A[6]),
    .A2(B[6]),
    .B1(\genblk1[6].FA.Cin ),
    .B2(\genblk1[6].FA.AxB ),
    .Y(\genblk1[6].FA.nCout )
  );
  AOI22 \genblk1[7].FA.XAxB  (
    .A1(A[7]),
    .A2(B[7]),
    .B1(\genblk1[7].FA.nA ),
    .B2(\genblk1[7].FA.nB ),
    .Y(\genblk1[7].FA.AxB )
  );
  NOT \genblk1[7].FA.XCin  (
    .A(\genblk1[6].FA.nCout ),
    .Y(\genblk1[7].FA.Cin )
  );
  AOI22 \genblk1[7].FA.XS  (
    .A1(\genblk1[7].FA.nAxB ),
    .A2(\genblk1[6].FA.nCout ),
    .B1(\genblk1[7].FA.AxB ),
    .B2(\genblk1[7].FA.Cin ),
    .Y(\genblk1[7].FA.S )
  );
  NOT \genblk1[7].FA.XnA  (
    .A(A[7]),
    .Y(\genblk1[7].FA.nA )
  );
  NOT \genblk1[7].FA.XnAxB  (
    .A(\genblk1[7].FA.AxB ),
    .Y(\genblk1[7].FA.nAxB )
  );
  NOT \genblk1[7].FA.XnB  (
    .A(B[7]),
    .Y(\genblk1[7].FA.nB )
  );
  AOI22 \genblk1[7].FA.XnCout  (
    .A1(A[7]),
    .A2(B[7]),
    .B1(\genblk1[7].FA.Cin ),
    .B2(\genblk1[7].FA.AxB ),
    .Y(\genblk1[7].FA.nCout )
  );
  assign S = { \genblk1[7].FA.S , \genblk1[6].FA.S , \genblk1[5].FA.S , \genblk1[4].FA.S , \genblk1[3].FA.S , \genblk1[2].FA.S , \genblk1[1].FA.S , \genblk1[0].FA.S  };
  assign \genblk1[0].FA.A  = A[0];
  assign \genblk1[0].FA.B  = B[0];
  assign \genblk1[0].FA.nCin  = nCin;
  assign \genblk1[1].FA.A  = A[1];
  assign \genblk1[1].FA.B  = B[1];
  assign \genblk1[1].FA.nCin  = \genblk1[0].FA.nCout ;
  assign \genblk1[2].FA.A  = A[2];
  assign \genblk1[2].FA.B  = B[2];
  assign \genblk1[2].FA.nCin  = \genblk1[1].FA.nCout ;
  assign \genblk1[3].FA.A  = A[3];
  assign \genblk1[3].FA.B  = B[3];
  assign \genblk1[3].FA.nCin  = \genblk1[2].FA.nCout ;
  assign \genblk1[4].FA.A  = A[4];
  assign \genblk1[4].FA.B  = B[4];
  assign \genblk1[4].FA.nCin  = \genblk1[3].FA.nCout ;
  assign \genblk1[5].FA.A  = A[5];
  assign \genblk1[5].FA.B  = B[5];
  assign \genblk1[5].FA.nCin  = \genblk1[4].FA.nCout ;
  assign \genblk1[6].FA.A  = A[6];
  assign \genblk1[6].FA.B  = B[6];
  assign \genblk1[6].FA.nCin  = \genblk1[5].FA.nCout ;
  assign \genblk1[7].FA.A  = A[7];
  assign \genblk1[7].FA.B  = B[7];
  assign \genblk1[7].FA.nCin  = \genblk1[6].FA.nCout ;
  assign \nC[-1]  = nCin;
  assign \nC[0]  = \genblk1[0].FA.nCout ;
  assign \nC[1]  = \genblk1[1].FA.nCout ;
  assign \nC[2]  = \genblk1[2].FA.nCout ;
  assign \nC[3]  = \genblk1[3].FA.nCout ;
  assign \nC[4]  = \genblk1[4].FA.nCout ;
  assign \nC[5]  = \genblk1[5].FA.nCout ;
  assign \nC[6]  = \genblk1[6].FA.nCout ;
  assign \nC[7]  = \genblk1[7].FA.nCout ;
  assign nCout = \genblk1[7].FA.nCout ;
endmodule
